//
// AADGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AADGroup: Codable {

    /** The id of the aad group */
    public var aadGroupId: UUID
    /** The id of the aad tenant */
    public var tenantId: UUID
    /** The display name of the aad group */
    public var displayName: String

    public init(aadGroupId: UUID, tenantId: UUID, displayName: String) {
        self.aadGroupId = aadGroupId
        self.tenantId = tenantId
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case aadGroupId = "aad_group_id"
        case tenantId = "tenant_id"
        case displayName = "display_name"
    }

}
