//
// AADTenantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AADTenantResponse: Codable {

    /** The AAD tenant id */
    public var aadTenantId: UUID
    /** The name of the AAD Tenant */
    public var displayName: String

    public init(aadTenantId: UUID, displayName: String) {
        self.aadTenantId = aadTenantId
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case aadTenantId = "aad_tenant_id"
        case displayName = "display_name"
    }

}
