//
// AADUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** an AAD user&#39;s id and tenant id */
public struct AADUser: Codable {

    /** the aad user&#39;s id */
    public var objectId: UUID
    /** the aad user&#39;s tenant id */
    public var tenantId: UUID

    public init(objectId: UUID, tenantId: UUID) {
        self.objectId = objectId
        self.tenantId = tenantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case objectId = "object_id"
        case tenantId = "tenant_id"
    }

}
