//
// ActiveCrashingAppDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ActiveCrashingAppDetails: Codable {

    public var nextLink: String?
    /** details of the apps with crashes */
    public var appsWithCrashes: [ActiveCrashingAppDetailsAppsWithCrashes]?

    public init(nextLink: String?, appsWithCrashes: [ActiveCrashingAppDetailsAppsWithCrashes]?) {
        self.nextLink = nextLink
        self.appsWithCrashes = appsWithCrashes
    }

}
