//
// AdministeredOrgsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AdministeredOrgsResponse: Codable {

    public var organizations: V01InvitationsSentOrganization

    public init(organizations: V01InvitationsSentOrganization) {
        self.organizations = organizations
    }

}
