//
// AlertBugTrackerRepoOwner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Repository owner object */
public struct AlertBugTrackerRepoOwner: Codable {

    public var name: String?
    public var id: String?
    public var login: String?

    public init(name: String?, id: String?, login: String?) {
        self.name = name
        self.id = id
        self.login = login
    }

}
