//
// AlertBugTrackerReposResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** List of bug tracker repositories */
public struct AlertBugTrackerReposResult: Codable {

    public enum RepoType: String, Codable, CaseIterable {
        case github = "github"
        case vsts = "vsts"
        case jira = "jira"
    }
    public var repoType: RepoType?
    public var repositories: [AlertBugTrackerReposResultRepositories]

    public init(repoType: RepoType?, repositories: [AlertBugTrackerReposResultRepositories]) {
        self.repoType = repoType
        self.repositories = repositories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case repoType = "repo_type"
        case repositories
    }

}
