//
// AlertingErrorAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AlertingErrorAllOf: Codable {

    /** The status code return by the API. It can be 400 or 404 or 409 or 500. */
    public var code: Int
    /** The reason for the request failed */
    public var message: String?

    public init(code: Int, message: String?) {
        self.code = code
        self.message = message
    }

}
