//
// AlertEmailSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Alerting Email Settings */
public struct AlertEmailSettings: Codable {

    /** The settings the user has for the app */
    public var settings: [AlertEmailSettingsSettings]

    public init(settings: [AlertEmailSettingsSettings]) {
        self.settings = settings
    }

}
