//
// AlertingError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Alerting service error */
public struct AlertingError: Codable {

    /** Unique request identifier for tracking */
    public var requestId: String
    /** The status code return by the API. It can be 400 or 404 or 409 or 500. */
    public var code: Int
    /** The reason for the request failed */
    public var message: String?

    public init(requestId: String, code: Int, message: String?) {
        self.requestId = requestId
        self.code = code
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case requestId = "request_id"
        case code
        case message
    }

}
