//
// AlertingGithubBugtrackerSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Github bugtracker specific settings */
public struct AlertingGithubBugtrackerSettings: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case github = "github"
        case vsts = "vsts"
        case jira = "jira"
    }
    public var ownerName: String
    /** type of bugtracker */
    public var type: ModelType
    public var githubRepoId: Int?
    public var githubRepoName: String?
    public var githubLabel: String?
    public var callbackUrl: String?

    public init(ownerName: String, type: ModelTypegithubRepoId: Int?, githubRepoName: String?, githubLabel: String?callbackUrl: String?, ) {
        self.ownerName = ownerName
        self.type = type
        self.githubRepoId = githubRepoId
        self.githubRepoName = githubRepoName
        self.githubLabel = githubLabel
        self.callbackUrl = callbackUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case ownerName = "owner_name"
        case type
        case githubRepoId = "github_repo_id"
        case githubRepoName = "github_repo_name"
        case githubLabel = "github_label"
        case callbackUrl = "callback_url"
    }

}
