//
// AllAccountsAggregatedBillingInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Aggregated Billing Information for a user an the organizations in which the user is an admin. */
public struct AllAccountsAggregatedBillingInformation: Codable {

    public var aggregatedBillings: InlineResponse20013?

    public init(aggregatedBillings: InlineResponse20013?) {
        self.aggregatedBillings = aggregatedBillings
    }

}
