//
// AndroidModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AndroidModule: Codable {

    /** Name of the Android module */
    public var name: String
    /** Module contains bundle settings */
    public var hasBundle: Bool?
    /** The product flavors of the Android module */
    public var productFlavors: [String]?
    /** The detected build variants of the Android module (matrix of product flavor + build type (debug|release)) */
    public var buildVariants: [String]?
    /** The detected build types of the Android module */
    public var buildTypes: [String]?
    /** The detected build configurations of the Android module */
    public var buildConfigurations: [AndroidProjectBuildConfigurations]?
    /** Whether the module is at the root level of the project */
    public var isRoot: Bool?

    public init(name: String, hasBundle: Bool?, productFlavors: [String]?, buildVariants: [String]?, buildTypes: [String]?, buildConfigurations: [AndroidProjectBuildConfigurations]?, isRoot: Bool?) {
        self.name = name
        self.hasBundle = hasBundle
        self.productFlavors = productFlavors
        self.buildVariants = buildVariants
        self.buildTypes = buildTypes
        self.buildConfigurations = buildConfigurations
        self.isRoot = isRoot
    }

}
