//
// ApiTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ApiTokenResponse: Codable {

    public enum Scope: String, Codable, CaseIterable {
        case all = "all"
        case inAppUpdate = "in_app_update"
        case viewer = "viewer"
    }
    /** The unique id (UUID) of the api token */
    public var id: UUID
    /** The creation time */
    public var createdAt: String
    /** The token&#39;s scope. A list of allowed roles. */
    public var scope: [Scope]?
    /** The encrypted value of a token. This value will only be returned for token of type in_app_update. */
    public var encryptedToken: String?
    /** The description of the token */
    public var description: String?

    public init(id: UUID, createdAt: String, scope: [Scope]?, encryptedToken: String?, description: String?) {
        self.id = id
        self.createdAt = createdAt
        self.scope = scope
        self.encryptedToken = encryptedToken
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case createdAt = "created_at"
        case scope
        case encryptedToken = "encrypted_token"
        case description
    }

}
