//
// ApiTokenGetUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ApiTokenGetUserResponse: Codable {

    public enum TokenScope: String, Codable, CaseIterable {
        case all = "all"
        case inAppUpdate = "in_app_update"
        case viewer = "viewer"
    }
    public enum UserOrigin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
        case codepush = "codepush"
    }
    /** The token&#39;s unique id (UUID) */
    public var tokenId: UUID
    /** The token&#39;s scope. A list of allowed roles. */
    public var tokenScope: [TokenScope]
    /** The user email */
    public var userEmail: String
    /** The unique id (UUID) of the user */
    public var userId: UUID
    /** The creation origin of the user who created this api token */
    public var userOrigin: UserOrigin

    public init(tokenId: UUID, tokenScope: [TokenScope], userEmail: String, userId: UUID, userOrigin: UserOrigin) {
        self.tokenId = tokenId
        self.tokenScope = tokenScope
        self.userEmail = userEmail
        self.userId = userId
        self.userOrigin = userOrigin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case tokenId = "token_id"
        case tokenScope = "token_scope"
        case userEmail = "user_email"
        case userId = "user_id"
        case userOrigin = "user_origin"
    }

}
