//
// AppDistributionGroupUsersRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppDistributionGroupUsersRequest: Codable {

    public var memberIds: [UUID]?

    public init(memberIds: [UUID]?) {
        self.memberIds = memberIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case memberIds = "member_ids"
    }

}
