//
// AppIntegrationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppIntegrationResponse: Codable {

    /** app id */
    public var appId: UUID

    public init(appId: UUID) {
        self.appId = appId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appId = "app_id"
    }

}
