//
// AppInvitationDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppInvitationDetailResponse: Codable {

    public enum InviteType: String, Codable, CaseIterable {
        case developer = "developer"
        case tester = "tester"
    }
    public enum Permissions: String, Codable, CaseIterable {
        case manager = "manager"
        case developer = "developer"
        case viewer = "viewer"
        case tester = "tester"
    }
    /** The unique ID (UUID) of the invitation */
    public var id: UUID
    public var app: Any
    /** The email address of the invited user */
    public var email: String
    /** The invitation type */
    public var inviteType: InviteType
    public var invitedBy: InlineResponse20020
    /** Indicates whether the invited user already exists */
    public var isExistingUser: Bool
    /** The permissions the user has for the app */
    public var permissions: [Permissions]?
    /** The number of apps in the group */
    public var appCount: Double?
    public var distributionGroup: AppInvitationDetailResponseDistributionGroup?

    public init(id: UUID, app: Any, email: String, inviteType: InviteType, invitedBy: InlineResponse20020, isExistingUser: Bool, permissions: [Permissions]?, appCount: Double?, distributionGroup: AppInvitationDetailResponseDistributionGroup?) {
        self.id = id
        self.app = app
        self.email = email
        self.inviteType = inviteType
        self.invitedBy = invitedBy
        self.isExistingUser = isExistingUser
        self.permissions = permissions
        self.appCount = appCount
        self.distributionGroup = distributionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case app
        case email
        case inviteType = "invite_type"
        case invitedBy = "invited_by"
        case isExistingUser = "is_existing_user"
        case permissions
        case appCount = "app_count"
        case distributionGroup = "distribution_group"
    }

}
