//
// AppleTestFlightGroupRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple details for fetching test flight groups from Apple Developer Portal. pass either apple_id or bundle_identifier to get the test flight groups. if both are passed than apple_id will take preference */
public struct AppleTestFlightGroupRequest: Codable {

    /** The username for the Apple Developer account. */
    public var username: String?
    /** The password for the Apple Developer account. */
    public var password: String?
    /** apple_id of the app for which test flight groups need to be fetched. */
    public var appleId: String?
    /** apple_id of the app for which test flight groups need to be fetched. */
    public var bundleIdentifier: String?
    /** Identifier of the team to use when logged in. */
    public var teamIdentifier: String?
    /** The 30-day session cookie for multi-factor authentication backed accounts. */
    public var cookie: String?
    /** The service_connection_id of the stored Apple credentials instead of username, password. */
    public var serviceConnectionId: String?

    public init(username: String?, password: String?, appleId: String?, bundleIdentifier: String?, teamIdentifier: String?, cookie: String?, serviceConnectionId: String?) {
        self.username = username
        self.password = password
        self.appleId = appleId
        self.bundleIdentifier = bundleIdentifier
        self.teamIdentifier = teamIdentifier
        self.cookie = cookie
        self.serviceConnectionId = serviceConnectionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case username
        case password
        case appleId = "apple_id"
        case bundleIdentifier = "bundle_identifier"
        case teamIdentifier = "team_identifier"
        case cookie
        case serviceConnectionId = "service_connection_id"
    }

}
