//
// AppleNotificationEndpointType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Type of endpoint the certificate or token are associated with */
public enum AppleNotificationEndpointType: String, Codable, CaseIterable {
    case production = "production"
    case sandbox = "sandbox"
}
