//
// AppleSecretDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple secret details */
public struct AppleSecretDetailsResponse: Codable {

    /** username to connect to apple store */
    public var username: String

    public init(username: String) {
        self.username = username
    }

}
