//
// AppleMutifactorLoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple credentials needed to log into the Apple Developer Portal */
public struct AppleMutifactorLoginRequest: Codable {

    /** The username for the Apple Developer account. */
    public var username: String
    /** This is the six digit OTP used for completing the multi-factor authentication */
    public var authcode: String

    public init(username: String, authcode: String) {
        self.username = username
        self.authcode = authcode
    }

}
