//
// AppleCertificateSecretDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple Certificate Secret Details */
public struct AppleCertificateSecretDetails: Codable {

    /** The certificate contents in base 64 encoded string */
    public var base64Certificate: String
    /** The password for the certificate */
    public var password: String
    /** The display name (CN) of the certificate */
    public var displayName: String
    /** The date-time from which the certificate is valid */
    public var certificateValidityStartDate: String
    /** The date-time till which the certificate is valid */
    public var certificateValidityEndDate: String

    public init(base64Certificate: String, password: String, displayName: String, certificateValidityStartDate: String, certificateValidityEndDate: String) {
        self.base64Certificate = base64Certificate
        self.password = password
        self.displayName = displayName
        self.certificateValidityStartDate = certificateValidityStartDate
        self.certificateValidityEndDate = certificateValidityEndDate
    }

}
