//
// ApplicationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ApplicationResponse: Codable {

    public var id: String?
    public var createdAt: Date?
    public var name: String?
    public var signInAudience: String?

    public init(id: String?, createdAt: Date?, name: String?, signInAudience: String?) {
        self.id = id
        self.createdAt = createdAt
        self.name = name
        self.signInAudience = signInAudience
    }

}
