//
// ApplicationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ApplicationsResponse: Codable {

    public var value: [ApplicationsResponseValue]?

    public init(value: [ApplicationsResponseValue]?) {
        self.value = value
    }

}
