//
// AppleMultifactorLoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The response of Multifactor login. This is a 30 day session token generated by apple. */
public struct AppleMultifactorLoginResponse: Codable {

    /** the apple developer account. */
    public var username: String?
    /** The 30-day session Token generated by apple after successfully logging in with Multifactor authentication. */
    public var cookie: String?
    /** The expiry date of the cookie generated by apple */
    public var expires: String?

    public init(username: String?, cookie: String?, expires: String?) {
        self.username = username
        self.cookie = cookie
        self.expires = expires
    }

}
