//
// AppMembershipsValidationResponseOrganizationAdminsWithMissingMemberships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppMembershipsValidationResponseOrganizationAdminsWithMissingMemberships: Codable {

    public var organizationId: String?
    public var userId: String?
    public var role: String?
    public var origin: String?

    public init(organizationId: String?, userId: String?, role: String?, origin: String?) {
        self.organizationId = organizationId
        self.userId = userId
        self.role = role
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case organizationId = "organization_id"
        case userId = "user_id"
        case role
        case origin
    }

}
