//
// AppMembershipsValidationResponseAppUsersWithMissingMemberships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppMembershipsValidationResponseAppUsersWithMissingMemberships: Codable {

    public var appId: String?
    public var userId: String?
    public var permissions: [String]?
    public var origin: String?

    public init(appId: String?, userId: String?, permissions: [String]?, origin: String?) {
        self.appId = appId
        self.userId = userId
        self.permissions = permissions
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appId = "app_id"
        case userId = "user_id"
        case permissions
        case origin
    }

}
