//
// AppMembershipsValidationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppMembershipsValidationResponse: Codable {

    public var excessAppMemberships: AppMembershipsValidationResponseExcessAppMemberships?
    public var appUsersWithMissingMemberships: [AppMembershipsValidationResponseAppUsersWithMissingMemberships]?
    public var distributionGroupUsersWithMissingMemberships: [AppMembershipsValidationResponseDistributionGroupUsersWithMissingMemberships]?
    public var organizationAdminsWithMissingMemberships: [AppMembershipsValidationResponseOrganizationAdminsWithMissingMemberships]?

    public init(excessAppMemberships: AppMembershipsValidationResponseExcessAppMemberships?, appUsersWithMissingMemberships: [AppMembershipsValidationResponseAppUsersWithMissingMemberships]?, distributionGroupUsersWithMissingMemberships: [AppMembershipsValidationResponseDistributionGroupUsersWithMissingMemberships]?, organizationAdminsWithMissingMemberships: [AppMembershipsValidationResponseOrganizationAdminsWithMissingMemberships]?) {
        self.excessAppMemberships = excessAppMemberships
        self.appUsersWithMissingMemberships = appUsersWithMissingMemberships
        self.distributionGroupUsersWithMissingMemberships = distributionGroupUsersWithMissingMemberships
        self.organizationAdminsWithMissingMemberships = organizationAdminsWithMissingMemberships
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case excessAppMemberships = "excess_app_memberships"
        case appUsersWithMissingMemberships = "app_users_with_missing_memberships"
        case distributionGroupUsersWithMissingMemberships = "distribution_group_users_with_missing_memberships"
        case organizationAdminsWithMissingMemberships = "organization_admins_with_missing_memberships"
    }

}
