//
// AppMembershipsResponseMemberships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppMembershipsResponseMemberships: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
        case codepush = "codepush"
        case testcloud = "testcloud"
        case hockeyappDogfood = "hockeyapp-dogfood"
    }
    public enum SourceType: String, Codable, CaseIterable {
        case user = "user"
        case org = "org"
        case distributionGroup = "distribution_group"
        case team = "team"
        case release = "release"
    }
    public var appId: String?
    public var userId: String?
    public var permissions: [String]?
    public var origin: Origin?
    public var sourceType: SourceType?
    public var sourceId: String?

    public init(appId: String?, userId: String?, permissions: [String]?, origin: Origin?, sourceType: SourceType?, sourceId: String?) {
        self.appId = appId
        self.userId = userId
        self.permissions = permissions
        self.origin = origin
        self.sourceType = sourceType
        self.sourceId = sourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appId = "app_id"
        case userId = "user_id"
        case permissions
        case origin
        case sourceType = "source_type"
        case sourceId = "source_id"
    }

}
