//
// AppMembershipsValidationResponseDistributionGroupUsersWithMissingMemberships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppMembershipsValidationResponseDistributionGroupUsersWithMissingMemberships: Codable {

    public var distributionGroupId: String?
    public var userId: String?
    public var origin: String?

    public init(distributionGroupId: String?, userId: String?, origin: String?) {
        self.distributionGroupId = distributionGroupId
        self.userId = userId
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case distributionGroupId = "distribution_group_id"
        case userId = "user_id"
        case origin
    }

}
