//
// AppResponseInternalAllOfUserPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** the permissions for the specified app user */
public struct AppResponseInternalAllOfUserPermissions: Codable {

    public enum Permissions: String, Codable, CaseIterable {
        case manager = "manager"
        case developer = "developer"
        case viewer = "viewer"
        case tester = "tester"
    }
    public var permissions: [Permissions]?
    public var userId: UUID?

    public init(permissions: [Permissions]?, userId: UUID?) {
        self.permissions = permissions
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case permissions
        case userId = "user_id"
    }

}
