//
// AppUserPermissionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppUserPermissionResponse: Codable {

    public enum Permissions: String, Codable, CaseIterable {
        case manager = "manager"
        case developer = "developer"
        case viewer = "viewer"
        case tester = "tester"
    }
    public enum AppOrigin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case codepush = "codepush"
    }
    /** The unique id (UUID) of the app */
    public var appId: UUID
    /** The permissions the user has for the app */
    public var permissions: [Permissions]
    /** The email of the user */
    public var userEmail: String
    /** The unique id (UUID) of the user */
    public var userId: UUID
    /** The creation origin of this app */
    public var appOrigin: AppOrigin
    /** A unique and secret key used to identify the app in communication with the ingestion endpoint for crash reporting and analytics */
    public var appSecret: String

    public init(appId: UUID, permissions: [Permissions], userEmail: String, userId: UUID, appOrigin: AppOrigin, appSecret: String) {
        self.appId = appId
        self.permissions = permissions
        self.userEmail = userEmail
        self.userId = userId
        self.appOrigin = appOrigin
        self.appSecret = appSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appId = "app_id"
        case permissions
        case userEmail = "user_email"
        case userId = "user_id"
        case appOrigin = "app_origin"
        case appSecret = "app_secret"
    }

}
