//
// AppVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppVersion: Codable {

    public var appVersionId: String
    public var appId: String
    public var displayName: String
    public var appVersion: String
    public var buildNumber: String?

    public init(appVersionId: String, appId: String, displayName: String, appVersion: String, buildNumber: String?) {
        self.appVersionId = appVersionId
        self.appId = appId
        self.displayName = displayName
        self.appVersion = appVersion
        self.buildNumber = buildNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appVersionId = "app_version_id"
        case appId = "app_id"
        case displayName = "display_name"
        case appVersion = "app_version"
        case buildNumber = "build_number"
    }

}
