//
// AudienceDevicePropertyValuesListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** List of device property values. */
public struct AudienceDevicePropertyValuesListResult: Codable {

    /** List of device property values. */
    public var values: [String]

    public init(values: [String]) {
        self.values = values
    }

}
