//
// AudienceListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** List of audiences. */
public struct AudienceListResult: Codable {

    /** List of audiences. */
    public var values: [AudienceListResultValues]
    public var nextLink: String?

    public init(values: [AudienceListResultValues], nextLink: String?) {
        self.values = values
        self.nextLink = nextLink
    }

}
