//
// AuthApplicationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuthApplicationResponse: Codable {

    public enum Provider: String, Codable, CaseIterable {
        case aadb2c = "AADB2C"
        case auth0 = "Auth0"
        case firebase = "Firebase"
        case aad = "AAD"
    }
    public var id: String
    public var provider: Provider
    public var tenantId: UUID?
    public var tenantName: String?
    public var policyId: String?
    public var scopeId: UUID?
    public var scopeUrl: String?
    public var signInAudience: String?

    public init(id: String, provider: Provider, tenantId: UUID?, tenantName: String?, policyId: String?, scopeId: UUID?, scopeUrl: String?, signInAudience: String?) {
        self.id = id
        self.provider = provider
        self.tenantId = tenantId
        self.tenantName = tenantName
        self.policyId = policyId
        self.scopeId = scopeId
        self.scopeUrl = scopeUrl
        self.signInAudience = signInAudience
    }

}
