//
// AvailableAppBuilds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AvailableAppBuilds: Codable {

    /** List of available app builds. */
    public var appBuilds: [String]?

    public init(appBuilds: [String]?) {
        self.appBuilds = appBuilds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appBuilds = "app_builds"
    }

}
