//
// AzureSubscriptionAddToAppRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AzureSubscriptionAddToAppRequest: Codable {

    /** The azure subscription id */
    public var subscriptionId: UUID

    public init(subscriptionId: UUID) {
        self.subscriptionId = subscriptionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case subscriptionId = "subscription_id"
    }

}
