//
// AzureSubscriptionAddRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AzureSubscriptionAddRequest: Codable {

    /** The azure subscription id */
    public var subscriptionId: UUID
    /** The tenant id of the azure subscription belongs to */
    public var tenantId: UUID
    /** The name of the azure subscription */
    public var subscriptionName: String
    /** If the subscription is used for billing */
    public var isBilling: Bool?

    public init(subscriptionId: UUID, tenantId: UUID, subscriptionName: String, isBilling: Bool?) {
        self.subscriptionId = subscriptionId
        self.tenantId = tenantId
        self.subscriptionName = subscriptionName
        self.isBilling = isBilling
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case subscriptionId = "subscription_id"
        case tenantId = "tenant_id"
        case subscriptionName = "subscription_name"
        case isBilling = "is_billing"
    }

}
