//
// BillingPlansSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Selection of a billing plan for one or more services */
public struct BillingPlansSelection: Codable {

    public var buildService: InlineResponse20013BillingPlansBuildServiceCurrentBillingPeriodByAccount?
    public var testService: InlineResponse20013BillingPlansBuildServiceCurrentBillingPeriodByAccount?

    public init(buildService: InlineResponse20013BillingPlansBuildServiceCurrentBillingPeriodByAccount?, testService: InlineResponse20013BillingPlansBuildServiceCurrentBillingPeriodByAccount?) {
        self.buildService = buildService
        self.testService = testService
    }

}
