//
// BranchConfigurationRevision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** branch configuration revision */
public struct BranchConfigurationRevision: Codable {

    public var id: String?
    public var revision: Double?
    public var changedDate: String?
    public var name: String?
    public var changeType: String?
    public var definitionUrl: String?
    public var changedBy: BranchConfigurationRevisionChangedBy?

    public init(id: String?, revision: Double?, changedDate: String?, name: String?, changeType: String?, definitionUrl: String?, changedBy: BranchConfigurationRevisionChangedBy?) {
        self.id = id
        self.revision = revision
        self.changedDate = changedDate
        self.name = name
        self.changeType = changeType
        self.definitionUrl = definitionUrl
        self.changedBy = changedBy
    }

}
