//
// BranchStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The branch build status */
public struct BranchStatus: Codable {

    public var configured: Bool
    public var lastBuild: InlineResponse20078?

    public init(configured: Bool, lastBuild: InlineResponse20078?) {
        self.configured = configured
        self.lastBuild = lastBuild
    }
    public var additionalProperties: [String:Any] = [:]

    public subscript(key: String) -> Any? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(configured, forKey: "configured")
        try container.encodeIfPresent(lastBuild, forKey: "lastBuild")
        try container.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        configured = try container.decode(Bool.self, forKey: "configured")
        lastBuild = try container.decodeIfPresent(InlineResponse20078.self, forKey: "lastBuild")
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("configured")
        nonAdditionalPropertyKeys.insert("lastBuild")
        additionalProperties = try container.decodeMap(Any.self, excludedKeys: nonAdditionalPropertyKeys)
    }


}
