//
// BugTrackerIssuesResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Returns a list of all issues associated with a repo */
public struct BugTrackerIssuesResult: Codable {

    public var issues: [BugTrackerIssuesResultIssues]?

    public init(issues: [BugTrackerIssuesResultIssues]?) {
        self.issues = issues
    }

}
