//
// BuildTimeline.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BuildTimeline: Codable {

    public var id: String?
    public var records: [BuildTimelineRecords]?

    public init(id: String?, records: [BuildTimelineRecords]?) {
        self.id = id
        self.records = records
    }

}
