//
// BuildTimelineRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BuildTimelineRecord: Codable {

    public var id: String?
    public var name: String?
    public var order: Double?
    public var percentComplete: Double?
    public var currentOperation: String?
    public var state: String?
    public var result: String?
    public var errorCount: Double?
    public var warningCount: Double?
    public var issues: [BuildTimelineIssues]?
    public var startTime: String?
    public var finishTime: String?
    public var type: String?

    public init(id: String?, name: String?, order: Double?, percentComplete: Double?, currentOperation: String?, state: String?, result: String?, errorCount: Double?, warningCount: Double?, issues: [BuildTimelineIssues]?, startTime: String?, finishTime: String?, type: String?) {
        self.id = id
        self.name = name
        self.order = order
        self.percentComplete = percentComplete
        self.currentOperation = currentOperation
        self.state = state
        self.result = result
        self.errorCount = errorCount
        self.warningCount = warningCount
        self.issues = issues
        self.startTime = startTime
        self.finishTime = finishTime
        self.type = type
    }

}
