//
// BuildLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BuildLog: Codable {

    public var value: [String]?

    public init(value: [String]?) {
        self.value = value
    }

}
