//
// BuildServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BuildServiceStatus: Codable {

    public var status: String?
    public var service: String?
    public var message: String?
    public var url: String?
    public var validUntil: Int?
    public var os: String?

    public init(status: String?, service: String?, message: String?, url: String?, validUntil: Int?, os: String?) {
        self.status = status
        self.service = service
        self.message = message
        self.url = url
        self.validUntil = validUntil
        self.os = os
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case status
        case service
        case message
        case url
        case validUntil = "valid_until"
        case os
    }

}
