//
// ClientIdResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This response contains the Azure AD B2C client ID for an application. */
public struct ClientIdResponse: Codable {

    public var clientId: String?

    public init(clientId: String?) {
        self.clientId = clientId
    }

}
