//
// CloseAccountOrganizationResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CloseAccountOrganizationResponseAllOf: Codable {

    /** The number of collaborators from the organization */
    public var collaboratorsCount: Double?

    public init(collaboratorsCount: Double?) {
        self.collaboratorsCount = collaboratorsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case collaboratorsCount = "collaborators_count"
    }

}
