//
// CodePushReleaseAllOf1DiffPackageMap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CodePushReleaseAllOf1DiffPackageMap: Codable {

    public var size: Double
    public var url: String

    public init(size: Double, url: String) {
        self.size = size
        self.url = url
    }

}
