//
// CodePushStatusMetricMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CodePushStatusMetricMetadata: Codable {

    public var deploymentKey: String
    public var label: String?
    public var appVersion: String?
    public var previousDeploymentKey: String?
    public var previousLabelOrAppVersion: String?
    public var status: String?
    public var clientUniqueId: String?

    public init(deploymentKey: String, label: String?, appVersion: String?, previousDeploymentKey: String?, previousLabelOrAppVersion: String?, status: String?, clientUniqueId: String?) {
        self.deploymentKey = deploymentKey
        self.label = label
        self.appVersion = appVersion
        self.previousDeploymentKey = previousDeploymentKey
        self.previousLabelOrAppVersion = previousLabelOrAppVersion
        self.status = status
        self.clientUniqueId = clientUniqueId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case deploymentKey = "deployment_key"
        case label
        case appVersion = "app_version"
        case previousDeploymentKey = "previous_deployment_key"
        case previousLabelOrAppVersion = "previous_label_or_app_version"
        case status
        case clientUniqueId = "client_unique_id"
    }

}
