//
// CodePushReleasePromoteAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CodePushReleasePromoteAllOf: Codable {

    public var label: String?

    public init(label: String?) {
        self.label = label
    }

}
