//
// CrashGroupOperatingSystem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CrashGroupOperatingSystem: Codable {

    /** OS name. */
    public var operatingSystemName: String?
    /** Count of OS. */
    public var crashCount: Int64?

    public init(operatingSystemName: String?, crashCount: Int64?) {
        self.operatingSystemName = operatingSystemName
        self.crashCount = crashCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case operatingSystemName = "operating_system_name"
        case crashCount = "crash_count"
    }

}
