//
// CrashDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CrashDetails: Codable {

    /** Carrier country code (for mobile devices).  */
    public var carrierCountry: String?
    /** Carrier name (for mobile devices).  */
    public var carrierName: String?
    /** Language code (example: en_US).  */
    public var locale: String
    /** OS build code (example: LMY47X).  */
    public var osBuild: String?
    /** Whether the device where the crash occurred is rooted or jailbroken  */
    public var rooted: Bool
    /** Screen size of the device in pixels (example: 640x480).  */
    public var screenSize: String
    /** Application launch timestamp (example: 1985-04-12T23:20:50.52Z).  */
    public var appStartTimestamp: Date?

    public init(carrierCountry: String?, carrierName: String?, locale: String, osBuild: String?, rooted: Bool, screenSize: String, appStartTimestamp: Date?) {
        self.carrierCountry = carrierCountry
        self.carrierName = carrierName
        self.locale = locale
        self.osBuild = osBuild
        self.rooted = rooted
        self.screenSize = screenSize
        self.appStartTimestamp = appStartTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case carrierCountry = "carrier_country"
        case carrierName = "carrier_name"
        case locale
        case osBuild = "os_build"
        case rooted
        case screenSize = "screen_size"
        case appStartTimestamp = "app_start_timestamp"
    }

}
