//
// CrashGroupChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CrashGroupChange: Codable {

    public enum Status: String, Codable, CaseIterable {
        case _open = "open"
        case closed = "closed"
        case ignored = "ignored"
    }
    public var status: Status?
    public var annotation: String?

    public init(status: Status?, annotation: String?) {
        self.status = status
        self.annotation = annotation
    }

}
