//
// CreateGdprTestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateGdprTestData: Codable {

    public var appId: UUID?
    public var accountId: UUID?
    public var userName: String?
    public var userEmail: String?
    public var appName: String?

    public init(appId: UUID?, accountId: UUID?, userName: String?, userEmail: String?, appName: String?) {
        self.appId = appId
        self.accountId = accountId
        self.userName = userName
        self.userEmail = userEmail
        self.appName = appName
    }

}
