//
// CreateAccessKeyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateAccessKeyRequest: Codable {

    /** Name of creator current access key */
    public var createdBy: String?
    /** Friendly name of the access key */
    public var friendlyName: String?
    /** Time to live of the access key */
    public var ttl: Double?

    public init(createdBy: String?, friendlyName: String?, ttl: Double?) {
        self.createdBy = createdBy
        self.friendlyName = friendlyName
        self.ttl = ttl
    }

}
