//
// CreateAccessKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateAccessKeyResponse: Codable {

    public var accessKey: CreateAccessKeyResponseAccessKey?

    public init(accessKey: CreateAccessKeyResponseAccessKey?) {
        self.accessKey = accessKey
    }

}
