//
// CustomPropertyLogDiagnostics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Set or remove custom properties. */
public struct CustomPropertyLogDiagnostics: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case event = "event"
        case page = "page"
        case startSession = "start_session"
        case error = "error"
        case pushInstallation = "push_installation"
        case startService = "start_service"
        case customProperties = "custom_properties"
    }
    /** Log type.  */
    public var type: ModelType
    /** Log creation timestamp.  */
    public var timestamp: Date
    /** Install ID.  */
    public var installId: UUID
    public var device: InlineResponse20041Device
    /** Custom property changes. */
    public var properties: [Any]?

    public init(type: ModelType, timestamp: Date, installId: UUID, device: InlineResponse20041Deviceproperties: [Any]?) {
        self.type = type
        self.timestamp = timestamp
        self.installId = installId
        self.device = device
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case timestamp
        case installId = "install_id"
        case device
        case properties
    }

}
