//
// DatabaseCollectionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DatabaseCollectionsResponse: Codable {

    public var value: [DataInstancesResponseValue]?

    public init(value: [DataInstancesResponseValue]?) {
        self.value = value
    }

}
