//
// DataSubjectRightEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DataSubjectRightEmailRequest: Codable {

    /** Email used for cancel delete with x-authz-bypass headers */
    public var email: String

    public init(email: String) {
        self.email = email
    }

}
