//
// DataSubjectRightQueueInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DataSubjectRightQueueInfo: Codable {

    public var sasUri: String
    public var queueName: String
    public var expiresAt: Date

    public init(sasUri: String, queueName: String, expiresAt: Date) {
        self.sasUri = sasUri
        self.queueName = queueName
        self.expiresAt = expiresAt
    }

}
