//
// Destination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Destination: Codable {

    public enum DestinationType: String, Codable, CaseIterable {
        case group = "group"
        case store = "store"
        case tester = "tester"
    }
    /** A name identifying a unique distribution group. */
    public var name: String?
    /** ID identifying a unique distribution group. */
    public var id: String
    /** Destination can be either store or group. */
    public var destinationType: DestinationType?
    /** Display name for the group or tester */
    public var displayName: String?
    /** Is the containing release the latest one in this distribution group. */
    public var isLatest: Bool?

    public init(name: String?, id: String, destinationType: DestinationType?, displayName: String?, isLatest: Bool?) {
        self.name = name
        self.id = id
        self.destinationType = destinationType
        self.displayName = displayName
        self.isLatest = isLatest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case id
        case destinationType = "destination_type"
        case displayName = "display_name"
        case isLatest = "is_latest"
    }

}
