//
// DeviceFrame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DeviceFrame: Codable {

    public var grid: V01AppsOwnerNameAppNameDeviceConfigurationsModelDeviceFrameGrid?
    public var full: V01AppsOwnerNameAppNameDeviceConfigurationsModelDeviceFrameGrid?

    public init(grid: V01AppsOwnerNameAppNameDeviceConfigurationsModelDeviceFrameGrid?, full: V01AppsOwnerNameAppNameDeviceConfigurationsModelDeviceFrameGrid?) {
        self.grid = grid
        self.full = full
    }

}
