//
// DeviceSetConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DeviceSetConfiguration: Codable {

    /** The unique id of the device configuration */
    public var id: UUID?
    public var image: DeviceSetImage?
    public var model: DeviceSetModel?
    public var os: String?
    public var osName: String?

    public init(id: UUID?, image: DeviceSetImage?, model: DeviceSetModel?, os: String?, osName: String?) {
        self.id = id
        self.image = image
        self.model = model
        self.os = os
        self.osName = osName
    }

}
