//
// DeviceDimensions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Physical device dimensions */
public struct DeviceDimensions: Codable {

    public var depth: Any?
    public var height: Any?
    public var width: Any?

    public init(depth: Any?, height: Any?, width: Any?) {
        self.depth = depth
        self.height = height
        self.width = width
    }

}
