//
// DeviceSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Short ID for a list of device IDs */
public struct DeviceSelection: Codable {

    /** Identifier of the device selection */
    public var shortId: String

    public init(shortId: String) {
        self.shortId = shortId
    }

}
