//
// DeviceSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The name and devices of the device set */
public struct DeviceSet: Codable {

    /** Identifier of the device set */
    public var id: String
    /** The number of manufacturers in the device set&#39;s device selection */
    public var manufacturerCount: Double?
    /** Name of the device set */
    public var name: String
    /** Slug of the device set */
    public var slug: String?
    public var owner: DeviceSetOwner
    /** The number of os versions in the device set&#39;s device selection */
    public var osVersionCount: Double?
    public var deviceConfigurations: [DeviceSetDeviceConfigurations]

    public init(id: String, manufacturerCount: Double?, name: String, slug: String?, owner: DeviceSetOwner, osVersionCount: Double?, deviceConfigurations: [DeviceSetDeviceConfigurations]) {
        self.id = id
        self.manufacturerCount = manufacturerCount
        self.name = name
        self.slug = slug
        self.owner = owner
        self.osVersionCount = osVersionCount
        self.deviceConfigurations = deviceConfigurations
    }

}
