//
// DistributionGroupAppsDeleteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DistributionGroupAppsDeleteRequest: Codable {

    /** The list of apps to delete from the distribution group */
    public var apps: [V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsBulkDeleteApps]?

    public init(apps: [V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsBulkDeleteApps]?) {
        self.apps = apps
    }

}
