//
// DistributionGroupsUserVerifyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DistributionGroupsUserVerifyRequest: Codable {

    /** An array of distribution group ids */
    public var distributionGroupIds: [InlineResponse2005]

    public init(distributionGroupIds: [InlineResponse2005]) {
        self.distributionGroupIds = distributionGroupIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case distributionGroupIds = "distribution_group_ids"
    }

}
