//
// DistributionGroupDetailsResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DistributionGroupDetailsResponseAllOf: Codable {

    public enum GroupType: String, Codable, CaseIterable {
        case _default = "Default"
        case hockeyAppDefault = "HockeyAppDefault"
        case microsoftDogfooding = "MicrosoftDogfooding"
    }
    /** Whether the distribution group is shared group or not */
    public var isShared: Bool?
    /** The count of apps associated with this distribution group */
    public var totalAppsCount: Double?
    /** The count of users in the distribution group */
    public var totalUserCount: Double?
    /** The count of non-pending users in the distribution group who will be notified by new releases */
    public var notifiedUserCount: Double?
    /** Type of group (Default, HockeyAppDefault or MicrosoftDogfooding) */
    public var groupType: GroupType?
    /** The distribution group users */
    public var users: [InlineResponse20010]?

    public init(isShared: Bool?, totalAppsCount: Double?, totalUserCount: Double?, notifiedUserCount: Double?, groupType: GroupType?, users: [InlineResponse20010]?) {
        self.isShared = isShared
        self.totalAppsCount = totalAppsCount
        self.totalUserCount = totalUserCount
        self.notifiedUserCount = notifiedUserCount
        self.groupType = groupType
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isShared = "is_shared"
        case totalAppsCount = "total_apps_count"
        case totalUserCount = "total_user_count"
        case notifiedUserCount = "notified_user_count"
        case groupType = "group_type"
        case users
    }

}
