//
// DistributionGroupAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DistributionGroupAllOf: Codable {

    /** Is the containing release the latest one in this distribution group. */
    public var isLatest: Bool?

    public init(isLatest: Bool?) {
        self.isLatest = isLatest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isLatest = "is_latest"
    }

}
