//
// ErrorAppBuilds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorAppBuilds: Codable {

    public var appBuilds: [String]?

    public init(appBuilds: [String]?) {
        self.appBuilds = appBuilds
    }

}
