//
// ErrorGroups.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorGroups: Codable {

    public var nextLink: String?
    public var errorGroups: [Any]?

    public init(nextLink: String?, errorGroups: [Any]?) {
        self.nextLink = nextLink
        self.errorGroups = errorGroups
    }

}
