//
// ErrorCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorCounts: Codable {

    /** total error count */
    public var count: Int64?
    /** the total error count for day */
    public var errors: [InlineResponse20053Errors]?

    public init(count: Int64?, errors: [InlineResponse20053Errors]?) {
        self.count = count
        self.errors = errors
    }

}
