//
// ErrorDownloadLink.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorDownloadLink: Codable {

    public var link: String

    public init(link: String) {
        self.link = link
    }

}
