//
// ErrorDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorDetails: Codable {

    public enum Code: String, Codable, CaseIterable {
        case badRequest = "BadRequest"
        case conflict = "Conflict"
        case notAcceptable = "NotAcceptable"
        case notFound = "NotFound"
        case internalServerError = "InternalServerError"
        case unauthorized = "Unauthorized"
        case tooManyRequests = "TooManyRequests"
    }
    public var code: Code
    public var message: String

    public init(code: Code, message: String) {
        self.code = code
        self.message = message
    }

}
