//
// ErrorAttachmentLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ErrorAttachmentLocation: Codable {

    public var uri: String?

    public init(uri: String?) {
        self.uri = uri
    }

}
