//
// Events.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Events: Codable {

    public var events: [EventsEvents]?
    /** The total count of events. */
    public var total: Int64?
    /** The active device over this period. */
    public var totalDevices: Int64?

    public init(events: [EventsEvents]?, total: Int64?, totalDevices: Int64?) {
        self.events = events
        self.total = total
        self.totalDevices = totalDevices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case events
        case total
        case totalDevices = "total_devices"
    }

}
