//
// EventPropertyValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An event property value with counts. */
public struct EventPropertyValue: Codable {

    /** The event property value name. */
    public var name: String?
    /** The count of the the event property value. */
    public var count: Int64?
    /** The count of previous time range of the event property value. */
    public var previousCount: Int64?

    public init(name: String?, count: Int64?, previousCount: Int64?) {
        self.name = name
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case count
        case previousCount = "previous_count"
    }

}
