//
// Exception.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** a exception */
public struct Exception: Codable {

    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case xamarin = "xamarin"
        case reactNative = "react-native"
        case ndk = "ndk"
        case unity = "unity"
        case other = "other"
    }
    /** Reason of the exception */
    public var reason: String?
    /** Type of the exception (NSSomethingException, NullPointerException) */
    public var type: String?
    /** frames of the excetpion */
    public var frames: [ExceptionFrames]
    /** relevant exception (crashed) */
    public var relevant: Bool?
    public var innerExceptions: [Exception]?
    /** SDK/Platform this thread is beeing generated from */
    public var platform: Platform?

    public init(reason: String?, type: String?, frames: [ExceptionFrames], relevant: Bool?, innerExceptions: [Exception]?, platform: Platform?) {
        self.reason = reason
        self.type = type
        self.frames = frames
        self.relevant = relevant
        self.innerExceptions = innerExceptions
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case reason
        case type
        case frames
        case relevant
        case innerExceptions = "inner_exceptions"
        case platform
    }

}
