//
// ExportEntity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum ExportEntity: String, Codable, CaseIterable {
    case crashes = "crashes"
    case errors = "errors"
    case attachments = "attachments"
    case noLogs = "no_logs"
}
