//
// ExternallyHostedReleaseCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A request containing information for creating an externally hosted release. */
public struct ExternallyHostedReleaseCreateRequest: Codable {

    /** The build version of the uploaded binary */
    public var buildVersion: String
    /** The build number of the uploaded binary */
    public var buildNumber: String?
    /** The external URL to the release&#39;s binary. */
    public var externalDownloadUrl: String

    public init(buildVersion: String, buildNumber: String?, externalDownloadUrl: String) {
        self.buildVersion = buildVersion
        self.buildNumber = buildNumber
        self.externalDownloadUrl = externalDownloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case buildVersion = "build_version"
        case buildNumber = "build_number"
        case externalDownloadUrl = "external_download_url"
    }

}
