//
// ExternalUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ExternalUserRequest: Codable {

    /** The token of the app invitation which lead to signup */
    public var appInvitation: String?
    /** The token of the test invitation which lead to signup */
    public var testerInvitation: String?
    /** The token of the organization invitation which lead to signup */
    public var organizationInvitation: String?
    /** The avatar URL of the user */
    public var avatarUrl: String?
    /** The full name of the user. Might for example be first and last name */
    public var displayName: String?
    /** The email address of the user */
    public var email: String
    /** The unique name that is used to identify the user. If no explicit value is given, a default will be auto-generated from the &#x60;display_name&#x60; value */
    public var name: String?

    public init(appInvitation: String?, testerInvitation: String?, organizationInvitation: String?, avatarUrl: String?, displayName: String?, email: String, name: String?) {
        self.appInvitation = appInvitation
        self.testerInvitation = testerInvitation
        self.organizationInvitation = organizationInvitation
        self.avatarUrl = avatarUrl
        self.displayName = displayName
        self.email = email
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appInvitation = "app_invitation"
        case testerInvitation = "tester_invitation"
        case organizationInvitation = "organization_invitation"
        case avatarUrl = "avatar_url"
        case displayName = "display_name"
        case email
        case name
    }

}
