//
// FeatureCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FeatureCreateRequest: Codable {

    /** The unique name of the feature */
    public var name: String
    /** The full (friendly) name of the feature. */
    public var displayName: String
    /** The state of the feature */
    public var state: Int?
    /** The friendly name of the feature */
    public var description: String?

    public init(name: String, displayName: String, state: Int?, description: String?) {
        self.name = name
        self.displayName = displayName
        self.state = state
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case displayName = "display_name"
        case state
        case description
    }

}
