//
// FeaturePatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FeaturePatchRequest: Codable {

    /** The friendly name of the feature */
    public var description: String?
    /** The full (friendly) name of the feature. */
    public var displayName: String?
    /** The state of the feature */
    public var state: Int?

    public init(description: String?, displayName: String?, state: Int?) {
        self.description = description
        self.displayName = displayName
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case description
        case displayName = "display_name"
        case state
    }

}
