//
// FeatureFlagsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FeatureFlagsResponse: Codable {

    public var featureFlags: [String]

    public init(featureFlags: [String]) {
        self.featureFlags = featureFlags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case featureFlags = "feature_flags"
    }

}
