//
// FileAsset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FileAsset: Codable {

    public var id: String?
    public var location: String?
    public var token: String?
    public var uploadDomain: String?
    public var uploadWindowLocation: String?
    public var urlEncodedToken: String?

    public init(id: String?, location: String?, token: String?, uploadDomain: String?, uploadWindowLocation: String?, urlEncodedToken: String?) {
        self.id = id
        self.location = location
        self.token = token
        self.uploadDomain = uploadDomain
        self.uploadWindowLocation = uploadWindowLocation
        self.urlEncodedToken = urlEncodedToken
    }

}
