//
// FilterVersionsContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FilterVersionsContainer: Codable {

    public var versions: [FilterVersionsContainerVersions]?

    public init(versions: [FilterVersionsContainerVersions]?) {
        self.versions = versions
    }

}
