//
// FilterVersionsContainerVersions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FilterVersionsContainerVersions: Codable {

    /** App version.  */
    public var version: String
    /** App build number.  */
    public var build: String

    public init(version: String, build: String) {
        self.version = version
        self.build = build
    }

}
