//
// GDPRInvitationDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GDPRInvitationDetailResponse: Codable {

    /** The id of the invitation */
    public var invitationId: UUID
    public var organization: V01InvitationsSentOrganization?
    public var app: Any?

    public init(invitationId: UUID, organization: V01InvitationsSentOrganization?, app: Any?) {
        self.invitationId = invitationId
        self.organization = organization
        self.app = app
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case invitationId = "invitation_id"
        case organization
        case app
    }

}
