//
// GdprVerificationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** GDPR tests verification result */
public struct GdprVerificationResult: Codable {

    /** Verification status. True means that the verification was successfull. */
    public var status: Bool?
    /** Optional error message if the verification failed. */
    public var message: String?

    public init(status: Bool?, message: String?) {
        self.status = status
        self.message = message
    }

}
