//
// GDPRPurgeVerifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GDPRPurgeVerifyResponse: Codable {

    /** indicate whether GDPR purge operation succeeds or not */
    public var success: Bool

    public init(success: Bool) {
        self.success = success
    }

}
