//
// GeneralDistributionGroupDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GeneralDistributionGroupDetailsResponse: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
    }
    /** The unique ID of the distribution group */
    public var id: UUID
    /** The name of the distribution group used in URLs */
    public var name: String
    /** The name of the distribution group */
    public var displayName: String?
    /** The creation origin of this distribution group */
    public var origin: Origin
    /** Whether the distribution group is public */
    public var isPublic: Bool
    /** Whether the distribution group is shared group or not */
    public var isShared: Bool?
    /** If distribution group is owned by an app, this is the unique app ID */
    public var ownerAppId: UUID?
    /** If distribution group is owned by an org, this is the unique org ID */
    public var ownerOrgId: UUID?

    public init(id: UUID, name: String, displayName: String?, origin: Origin, isPublic: Bool, isShared: Bool?, ownerAppId: UUID?, ownerOrgId: UUID?) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.origin = origin
        self.isPublic = isPublic
        self.isShared = isShared
        self.ownerAppId = ownerAppId
        self.ownerOrgId = ownerOrgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case displayName = "display_name"
        case origin
        case isPublic = "is_public"
        case isShared = "is_shared"
        case ownerAppId = "owner_app_id"
        case ownerOrgId = "owner_org_id"
    }

}
