//
// GeneralDistributionGroupDetailsResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GeneralDistributionGroupDetailsResponseAllOf: Codable {

    /** Whether the distribution group is shared group or not */
    public var isShared: Bool?
    /** If distribution group is owned by an app, this is the unique app ID */
    public var ownerAppId: UUID?
    /** If distribution group is owned by an org, this is the unique org ID */
    public var ownerOrgId: UUID?

    public init(isShared: Bool?, ownerAppId: UUID?, ownerOrgId: UUID?) {
        self.isShared = isShared
        self.ownerAppId = ownerAppId
        self.ownerOrgId = ownerOrgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isShared = "is_shared"
        case ownerAppId = "owner_app_id"
        case ownerOrgId = "owner_org_id"
    }

}
