//
// GetInAppUpdateTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GetInAppUpdateTokenResponse: Codable {

    /** The api token generated will not be accessible again */
    public var token: String

    public init(token: String) {
        self.token = token
    }

}
