//
// GitHubInstallationRepository.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The repository which is accessiable by GitHub App Installation */
public struct GitHubInstallationRepository: Codable {

    /** The repository name */
    public var name: String?
    /** The discription of repository */
    public var description: String?
    /** URL used to clone the repository */
    public var cloneUrl: String?
    /** The default branch for the repo */
    public var defaultBranch: String?
    /** The language in the repository */
    public var language: String?
    /** The repository updated time */
    public var updatedAt: String?
    /** Whether the repository is a fork */
    public var fork: Bool?

    public init(name: String?, description: String?, cloneUrl: String?, defaultBranch: String?, language: String?, updatedAt: String?, fork: Bool?) {
        self.name = name
        self.description = description
        self.cloneUrl = cloneUrl
        self.defaultBranch = defaultBranch
        self.language = language
        self.updatedAt = updatedAt
        self.fork = fork
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case description
        case cloneUrl = "clone_url"
        case defaultBranch = "default_branch"
        case language
        case updatedAt = "updated_at"
        case fork
    }

}
