//
// GitHubMarketplacePurchasePlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** GitHub Marketplace plan */
public struct GitHubMarketplacePurchasePlan: Codable {

    /** Id of the GitHub plan */
    public var id: Int?

    public init(id: Int?) {
        self.id = id
    }

}
