//
// HandledErrorDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HandledErrorDetails: Codable {

    public var name: String?
    public var reasonFrames: [Any]?
    /** Timestamp when the app was launched, example: &#39;2017-03-13T18:05:42Z&#39;.  */
    public var appLaunchTimestamp: Date?
    /** Carrier name (for mobile devices).  */
    public var carrierName: String?
    /** Flag indicating if device is jailbroken  */
    public var jailbreak: Bool?
    public var properties: [String:String]?
    public var errorId: String?
    public var timestamp: Date?
    public var deviceName: String?
    public var osVersion: String?
    public var osType: String?
    public var country: String?
    public var language: String?
    public var userId: String?
    public var hasBreadcrumbs: Bool?
    public var hasAttachments: Bool?

    public init(name: String?, reasonFrames: [Any]?, appLaunchTimestamp: Date?, carrierName: String?, jailbreak: Bool?, properties: [String:String]?errorId: String?, timestamp: Date?, deviceName: String?, osVersion: String?, osType: String?, country: String?, language: String?, userId: String?, hasBreadcrumbs: Bool?, hasAttachments: Bool?) {
        self.name = name
        self.reasonFrames = reasonFrames
        self.appLaunchTimestamp = appLaunchTimestamp
        self.carrierName = carrierName
        self.jailbreak = jailbreak
        self.properties = properties
        self.errorId = errorId
        self.timestamp = timestamp
        self.deviceName = deviceName
        self.osVersion = osVersion
        self.osType = osType
        self.country = country
        self.language = language
        self.userId = userId
        self.hasBreadcrumbs = hasBreadcrumbs
        self.hasAttachments = hasAttachments
    }

}
