//
// HasBuildUploadedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The response for the build uploaded check. */
public struct HasBuildUploadedResponse: Codable {

    /** true if a build has been uploaded, false otherwise */
    public var hasBuildUploaded: Bool?

    public init(hasBuildUploaded: Bool?) {
        self.hasBuildUploaded = hasBuildUploaded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case hasBuildUploaded = "has_build_uploaded"
    }

}
