//
// InlineObject66.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple Mapping Request Type */
public struct InlineObject66: Codable {

    /** Id for the shared service connection. In case of Apple AppStore, this connection will be used to create and connect to the Apple AppStore in Mobile Center. */
    public var serviceConnectionId: String
    /** ID of the apple application in apple store, takes precedence over bundle_identifier when both are provided */
    public var appleId: String?
    /** Bundle Identifier of the apple package */
    public var bundleIdentifier: String?
    /** ID of the Team associated with the app in apple store */
    public var teamIdentifier: String

    public init(serviceConnectionId: String, appleId: String?, bundleIdentifier: String?, teamIdentifier: String) {
        self.serviceConnectionId = serviceConnectionId
        self.appleId = appleId
        self.bundleIdentifier = bundleIdentifier
        self.teamIdentifier = teamIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case serviceConnectionId = "service_connection_id"
        case appleId = "apple_id"
        case bundleIdentifier = "bundle_identifier"
        case teamIdentifier = "team_identifier"
    }

}
