//
// InlineObject64.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject64: Codable {

    /** Version to build which represents the full Git commit reference */
    public var sourceVersion: String?
    /** Run build in debug mode */
    public var debug: Bool?

    public init(sourceVersion: String?, debug: Bool?) {
        self.sourceVersion = sourceVersion
        self.debug = debug
    }

}
