//
// InlineResponse20083.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20083: Codable {

    /** The ISO 8601 datetime. */
    public var datetime: String?
    /** Count of the object. */
    public var count: Int64?

    public init(datetime: String?, count: Int64?) {
        self.datetime = datetime
        self.count = count
    }

}
