//
// InlineResponse20027.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20027: Codable {

    public var resources: [InlineResponse20027Resources]?

    public init(resources: [InlineResponse20027Resources]?) {
        self.resources = resources
    }

}
