//
// InlineResponse20014.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20014: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
    }
    /** The display name of the organization */
    public var displayName: String
    /** The slug name of the organization */
    public var name: String
    /** The creation origin of this organization */
    public var origin: Origin

    public init(displayName: String, name: String, origin: Origin) {
        self.displayName = displayName
        self.name = name
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case displayName = "display_name"
        case name
        case origin
    }

}
