//
// InlineObject73.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject73: Codable {

    public enum Scope: String, Codable, CaseIterable {
        case all = "all"
        case viewer = "viewer"
    }
    /** The description of the token */
    public var description: String?
    /** The scope for this token. */
    public var scope: [Scope]?

    public init(description: String?, scope: [Scope]?) {
        self.description = description
        self.scope = scope
    }

}
