//
// InlineResponse20092CountPerSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20092CountPerSession: Codable {

    /** The ISO 8601 datetime. */
    public var datetime: String?
    /** Decimal count of the object. */
    public var count: Double?

    public init(datetime: String?, count: Double?) {
        self.datetime = datetime
        self.count = count
    }

}
