//
// InlineResponse20084Oses.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20084Oses: Codable {

    /** OS name. */
    public var osName: String?
    /** Count current of OS. */
    public var count: Int64?
    /** Count of previous OS. */
    public var previousCount: Int64?

    public init(osName: String?, count: Int64?, previousCount: Int64?) {
        self.osName = osName
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case osName = "os_name"
        case count
        case previousCount = "previous_count"
    }

}
