//
// InlineResponse20023.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20023: Codable {

    public var appUploadId: UUID?
    public var testParameters: Any?

    public init(appUploadId: UUID?, testParameters: Any?) {
        self.appUploadId = appUploadId
        self.testParameters = testParameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appUploadId = "app_upload_id"
        case testParameters = "test_parameters"
    }

}
