//
// InlineResponse20092.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20092: Codable {

    public var avgCountPerSession: Double?
    public var previousAvgCountPerSession: Double?
    public var countPerSession: [InlineResponse20092CountPerSession]?

    public init(avgCountPerSession: Double?, previousAvgCountPerSession: Double?, countPerSession: [InlineResponse20092CountPerSession]?) {
        self.avgCountPerSession = avgCountPerSession
        self.previousAvgCountPerSession = previousAvgCountPerSession
        self.countPerSession = countPerSession
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case avgCountPerSession = "avg_count_per_session"
        case previousAvgCountPerSession = "previous_avg_count_per_session"
        case countPerSession = "count_per_session"
    }

}
