//
// InlineResponse20095.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20095: Codable {

    /** Average percentage. */
    public var averagePercentage: Double?
    /** The crash-free percentage per day. */
    public var dailyPercentages: [InlineResponse20095DailyPercentages]?

    public init(averagePercentage: Double?, dailyPercentages: [InlineResponse20095DailyPercentages]?) {
        self.averagePercentage = averagePercentage
        self.dailyPercentages = dailyPercentages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case averagePercentage = "average_percentage"
        case dailyPercentages = "daily_percentages"
    }

}
