//
// InlineResponse20058.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20058: Codable {

    public var appBuilds: [String]?

    public init(appBuilds: [String]?) {
        self.appBuilds = appBuilds
    }

}
