//
// InlineResponse20082Distribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20082Distribution: Codable {

    /** The bucket name. */
    public var bucket: String?
    /** The count of sessions in current bucket. */
    public var count: Int64?

    public init(bucket: String?, count: Int64?) {
        self.bucket = bucket
        self.count = count
    }

}
