//
// InlineResponse20087Languages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20087Languages: Codable {

    /** Language&#39;s name. */
    public var languageName: String?
    /** Count current of language. */
    public var count: Int64?
    /** Count of previous lanugage. */
    public var previousCount: Int64?

    public init(languageName: String?, count: Int64?, previousCount: Int64?) {
        self.languageName = languageName
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case languageName = "language_name"
        case count
        case previousCount = "previous_count"
    }

}
