//
// InlineResponse20063.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20063: Codable {

    /** The code of the result */
    public var code: String?
    /** The message of the result */
    public var message: Int?
    /** The status code of the result */
    public var status: Int
    /** The email of the user */
    public var userEmail: String?

    public init(code: String?, message: Int?, status: Int, userEmail: String?) {
        self.code = code
        self.message = message
        self.status = status
        self.userEmail = userEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case code
        case message
        case status
        case userEmail = "user_email"
    }

}
