//
// InlineResponseDefault3Error.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponseDefault3Error: Codable {

    /** The status code return by the API. It can be 400 or 403 or 500. */
    public var code: Int?
    /** The reason for the request failed */
    public var message: String?

    public init(code: Int?, message: String?) {
        self.code = code
        self.message = message
    }

}
