//
// InlineResponse20099.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20099: Codable {

    /** Total crash count. */
    public var count: Int64?
    /** The total crash count for day. */
    public var crashes: [InlineResponse20083]?

    public init(count: Int64?, crashes: [InlineResponse20083]?) {
        self.count = count
        self.crashes = crashes
    }

}
