//
// InlineResponse20042.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20042: Codable {

    public var content: String?

    public init(content: String?) {
        self.content = content
    }

}
