//
// InlineResponse2004.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2004: Codable {

    /** The unique ID (UUID) of the app */
    public var id: String?
    public var release: Any?
    /** The app&#39;s name. */
    public var name: String?
    /** The app&#39;s display name. */
    public var displayName: String?
    /** The description of the app */
    public var description: String?
    /** A URL to the app&#39;s icon. */
    public var iconUrl: String?
    /** The app&#39;s os. */
    public var os: String?
    public var owner: V01TesterAppsOwner?

    public init(id: String?, release: Any?, name: String?, displayName: String?, description: String?, iconUrl: String?, os: String?, owner: V01TesterAppsOwner?) {
        self.id = id
        self.release = release
        self.name = name
        self.displayName = displayName
        self.description = description
        self.iconUrl = iconUrl
        self.os = os
        self.owner = owner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case release
        case name
        case displayName = "display_name"
        case description
        case iconUrl = "icon_url"
        case os
        case owner
    }

}
