//
// InlineResponse20079.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20079: Codable {

    public var value: [InlineResponse20079Value]

    public init(value: [InlineResponse20079Value]) {
        self.value = value
    }

}
