//
// InlineResponseDefault4.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Error */
public struct InlineResponseDefault4: Codable {

    public var error: InlineResponseDefault4Error?

    public init(error: InlineResponseDefault4Error?) {
        self.error = error
    }

}
