//
// InlineResponse20051.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20051: Codable {

    public var appId: String?
    public var errorGroupId: String?
    public var errorId: String?
    public var errorsDeleted: Int?
    public var attachmentsDeleted: Int?
    public var blobsSucceeded: Int?
    public var blobsFailed: Int?

    public init(appId: String?, errorGroupId: String?, errorId: String?, errorsDeleted: Int?, attachmentsDeleted: Int?, blobsSucceeded: Int?, blobsFailed: Int?) {
        self.appId = appId
        self.errorGroupId = errorGroupId
        self.errorId = errorId
        self.errorsDeleted = errorsDeleted
        self.attachmentsDeleted = attachmentsDeleted
        self.blobsSucceeded = blobsSucceeded
        self.blobsFailed = blobsFailed
    }

}
