//
// InlineResponse20037.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Export status */
public struct InlineResponse20037: Codable {

    public enum Status: String, Codable, CaseIterable {
        case inProgress = "InProgress"
        case completed = "Completed"
        case failed = "Failed"
    }
    /** The unique export identifier. */
    public var exportId: String
    /** Status of the export. */
    public var status: Status

    public init(exportId: String, status: Status) {
        self.exportId = exportId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case exportId = "export_id"
        case status
    }

}
