//
// InlineResponse400.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse400: Codable {

    public var destinations: [InlineResponse400Destinations]?
    public var mandatoryUpdate: Bool?
    public var releaseNotes: String?

    public init(destinations: [InlineResponse400Destinations]?, mandatoryUpdate: Bool?, releaseNotes: String?) {
        self.destinations = destinations
        self.mandatoryUpdate = mandatoryUpdate
        self.releaseNotes = releaseNotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case destinations
        case mandatoryUpdate = "mandatory_update"
        case releaseNotes = "release_notes"
    }

}
