//
// InlineResponseDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Alerting service error */
public struct InlineResponseDefault: Codable {

    /** Unique request identifier for tracking */
    public var requestId: String

    public init(requestId: String) {
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case requestId = "request_id"
    }

}
