//
// InlineObject30.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A request containing information pertaining to starting a symbol upload process */
public struct InlineObject30: Codable {

    public enum SymbolType: String, Codable, CaseIterable {
        case apple = "Apple"
        case javaScript = "JavaScript"
        case breakpad = "Breakpad"
        case androidProguard = "AndroidProguard"
        case uwp = "UWP"
    }
    /** The type of the symbol for the current symbol upload */
    public var symbolType: SymbolType
    /** The callback URL that the client can optionally provide to get status updates for the current symbol upload */
    public var clientCallback: String?
    /** The file name for the symbol upload */
    public var fileName: String?
    /** The build number. Optional for Apple. Required for Android. */
    public var build: String?
    /** The version number. Optional for Apple. Required for Android. */
    public var version: String?

    public init(symbolType: SymbolType, clientCallback: String?, fileName: String?, build: String?, version: String?) {
        self.symbolType = symbolType
        self.clientCallback = clientCallback
        self.fileName = fileName
        self.build = build
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case symbolType = "symbol_type"
        case clientCallback = "client_callback"
        case fileName = "file_name"
        case build
        case version
    }

}
