//
// InlineResponse20066.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20066: Codable {

    public var key: String?
    public var name: String
    public var latestRelease: Any?

    public init(key: String?, name: String, latestRelease: Any?) {
        self.key = key
        self.name = name
        self.latestRelease = latestRelease
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case key
        case name
        case latestRelease = "latest_release"
    }

}
