//
// InlineResponse20098Models.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20098Models: Codable {

    /** Model&#39;s name. */
    public var modelName: String?
    /** Count of model. */
    public var crashCount: Int64?

    public init(modelName: String?, crashCount: Int64?) {
        self.modelName = modelName
        self.crashCount = crashCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case modelName = "model_name"
        case crashCount = "crash_count"
    }

}
