//
// InlineResponse20065.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20065: Codable {

    public var label: String
    public var active: Int
    public var downloaded: Int?
    public var failed: Int?
    public var installed: Int?

    public init(label: String, active: Int, downloaded: Int?, failed: Int?, installed: Int?) {
        self.label = label
        self.active = active
        self.downloaded = downloaded
        self.failed = failed
        self.installed = installed
    }

}
