//
// InlineObject42.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Generic export configuration. */
public struct InlineObject42: Codable {

    /** A shared access signature (SAS) URI with Read, Write and Delete permissions on a container. */
    public var blobContainerSasUri: String

    public init(blobContainerSasUri: String) {
        self.blobContainerSasUri = blobContainerSasUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case blobContainerSasUri = "blob_container_sas_uri"
    }

}
