//
// InlineResponse20027Resources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20027Resources: Codable {

    public var rel: String?
    public var path: String?

    public init(rel: String?, path: String?) {
        self.rel = rel
        self.path = path
    }

}
