//
// InlineResponse20085Models.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20085Models: Codable {

    /** Model&#39;s name. */
    public var modelName: String?
    /** Count current of model. */
    public var count: Int64?
    /** Count of previous model. */
    public var previousCount: Int64?

    public init(modelName: String?, count: Int64?, previousCount: Int64?) {
        self.modelName = modelName
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case modelName = "model_name"
        case count
        case previousCount = "previous_count"
    }

}
