//
// InlineResponse20080.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple Test Flight Groups Response Type */
public struct InlineResponse20080: Codable {

    /** id of the group. */
    public var id: String?
    /** provider id of the group. */
    public var providerId: Double?
    /** apple id of the group. */
    public var appleId: Double?
    /** name of the group. */
    public var name: String?

    public init(id: String?, providerId: Double?, appleId: Double?, name: String?) {
        self.id = id
        self.providerId = providerId
        self.appleId = appleId
        self.name = name
    }

}
