//
// InlineResponse20046.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20046: Codable {

    public var retentionInDays: Int

    public init(retentionInDays: Int) {
        self.retentionInDays = retentionInDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case retentionInDays = "retention_in_days"
    }

}
