//
// InlineResponseDefault1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponseDefault1: Codable {

    public var error: InlineResponseDefault1Error

    public init(error: InlineResponseDefault1Error) {
        self.error = error
    }

}
