//
// InlineObject67.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject67: Codable {

    public var releases: [V01AppsOwnerNameAppNameAnalyticsDistributionReleaseCountsReleases]

    public init(releases: [V01AppsOwnerNameAppNameAnalyticsDistributionReleaseCountsReleases]) {
        self.releases = releases
    }

}
