//
// InlineResponse20073.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Location for downloading crash raw */
public struct InlineResponse20073: Codable {

    public var uri: String

    public init(uri: String) {
        self.uri = uri
    }

}
