//
// InlineResponse201.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse201: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
    }
    /** The unique ID of the distribution group */
    public var id: UUID
    /** The name of the distribution group used in URLs */
    public var name: String
    /** The name of the distribution group */
    public var displayName: String?
    /** The creation origin of this distribution group */
    public var origin: Origin
    /** Whether the distribution group is public */
    public var isPublic: Bool

    public init(id: UUID, name: String, displayName: String?, origin: Origin, isPublic: Bool) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.origin = origin
        self.isPublic = isPublic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case displayName = "display_name"
        case origin
        case isPublic = "is_public"
    }

}
