//
// InlineResponse200100.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse200100: Codable {

    public var crashGroupId: String?
    public var appVersion: String?
    public var overall: InlineResponse20096?

    public init(crashGroupId: String?, appVersion: String?, overall: InlineResponse20096?) {
        self.crashGroupId = crashGroupId
        self.appVersion = appVersion
        self.overall = overall
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case crashGroupId = "crash_group_id"
        case appVersion = "app_version"
        case overall
    }

}
