//
// InlineObject24.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject24: Codable {

    /** The full (friendly) name of the organization. */
    public var displayName: String?
    /** The name of the organization used in URLs */
    public var name: String?

    public init(displayName: String?, name: String?) {
        self.displayName = displayName
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case displayName = "display_name"
        case name
    }

}
