//
// InlineObject10.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject10: Codable {

    /** The new display name of the team */
    public var displayName: String

    public init(displayName: String) {
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case displayName = "display_name"
    }

}
