//
// InlineObject20.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject20: Codable {

    /** The list of apps to add to distribution group */
    public var apps: [V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsApps]?

    public init(apps: [V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsApps]?) {
        self.apps = apps
    }

}
