//
// InlineResponse20094.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20094: Codable {

    public var total: Int64?
    public var counts: [InlineResponse20094Counts]

    public init(total: Int64?, counts: [InlineResponse20094Counts]) {
        self.total = total
        self.counts = counts
    }

}
