//
// InlineObject49.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject49: Codable {

    /** Service connection id to updated. */
    public var serviceConnectionId: String

    public init(serviceConnectionId: String) {
        self.serviceConnectionId = serviceConnectionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case serviceConnectionId = "service_connection_id"
    }

}
