//
// InlineResponse20082.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20082: Codable {

    /** The count of sessions in these buckets. */
    public var distribution: [InlineResponse20082Distribution]?
    /** The previous average session duration for previous time range. */
    public var previousAverageDuration: String?
    /** The average session duration for current time range. */
    public var averageDuration: String?

    public init(distribution: [InlineResponse20082Distribution]?, previousAverageDuration: String?, averageDuration: String?) {
        self.distribution = distribution
        self.previousAverageDuration = previousAverageDuration
        self.averageDuration = averageDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case distribution
        case previousAverageDuration = "previous_average_duration"
        case averageDuration = "average_duration"
    }

}
