//
// InlineObject38.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A request containing information pertaining to begin a release upload process */
public struct InlineObject38: Codable {

    /** Optional value for explicitly specifying the ID of existing release. */
    public var releaseId: Double?
    /** The build version of the uploaded binary, used for macOS, Windows and Custom app support. */
    public var buildVersion: String?
    /** The build number of the uploaded binary, used with build_version for macOS app support. */
    public var buildNumber: String?

    public init(releaseId: Double?, buildVersion: String?, buildNumber: String?) {
        self.releaseId = releaseId
        self.buildVersion = buildVersion
        self.buildNumber = buildNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case releaseId = "release_id"
        case buildVersion = "build_version"
        case buildNumber = "build_number"
    }

}
