//
// InlineResponse20038.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Alerting Email Settings of the user for a particular app */
public struct InlineResponse20038: Codable {

    /** Unique request identifier for tracking */
    public var requestId: String

    public init(requestId: String) {
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case requestId = "request_id"
    }

}
