//
// InnerError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InnerError: Codable {

    public var code: String?
    public var innererror: InnerError?

    public init(code: String?, innererror: InnerError?) {
        self.code = code
        self.innererror = innererror
    }

}
