//
// InternalUserSignupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InternalUserSignupResponse: Codable {

    public enum Status: String, Codable, CaseIterable {
        case complete = "Complete"
        case needsVerification = "NeedsVerification"
    }
    /** The unique id (UUID) of the user */
    public var id: UUID
    /** The full name of the user. Might for example be first and last name */
    public var displayName: String
    /** The email address of the user */
    public var email: String
    /** The name of the external auth provider */
    public var externalProvider: String?
    /** The user ID given by the external provider */
    public var externalUserId: String?
    /** The unique name that is used to identify the user. */
    public var name: String
    /** The current status of the user record after signup */
    public var status: Status?

    public init(id: UUID, displayName: String, email: String, externalProvider: String?, externalUserId: String?, name: String, status: Status?) {
        self.id = id
        self.displayName = displayName
        self.email = email
        self.externalProvider = externalProvider
        self.externalUserId = externalUserId
        self.name = name
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case displayName = "display_name"
        case email
        case externalProvider = "external_provider"
        case externalUserId = "external_user_id"
        case name
        case status
    }

}
