//
// IntuneStoreResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneStoreResponse: Codable {

    public var targetAudience: V01AppsOwnerNameAppNameDistributionStoresIntuneDetailsTargetAudience?
    public var appCategory: V01AppsOwnerNameAppNameDistributionStoresIntuneDetailsAppCategory?

    public init(targetAudience: V01AppsOwnerNameAppNameDistributionStoresIntuneDetailsTargetAudience?, appCategory: V01AppsOwnerNameAppNameDistributionStoresIntuneDetailsAppCategory?) {
        self.targetAudience = targetAudience
        self.appCategory = appCategory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case targetAudience = "target_audience"
        case appCategory = "app_category"
    }

}
