//
// IntuneGroups.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneGroups: Codable {

    /** context */
    public var odataContext: String?
    /** categories for intune app */
    public var value: [IntuneGroupsValue]?

    public init(odataContext: String?, value: [IntuneGroupsValue]?) {
        self.odataContext = odataContext
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case odataContext = "odata.context"
        case value
    }

}
