//
// IntuneAppCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneAppCategory: Codable {

    /** display name for the app category */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }

}
