//
// IntuneAppCategoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneAppCategoryResponse: Codable {

    /** display name for the app category */
    public var name: String?
    /** ID for the category. */
    public var id: String?

    public init(name: String?, id: String?) {
        self.name = name
        self.id = id
    }

}
