//
// IntuneStoreRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneStoreRequest: Codable {

    public var secretJson: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1SecretJson?
    public var targetAudience: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1TargetAudience?
    public var appCategory: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1AppCategory?
    /** tenant id of the intune store */
    public var tenantId: String?

    public init(secretJson: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1SecretJson?, targetAudience: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1TargetAudience?, appCategory: V01AppsOwnerNameAppNameDistributionStoresIntuneDetails1AppCategory?, tenantId: String?) {
        self.secretJson = secretJson
        self.targetAudience = targetAudience
        self.appCategory = appCategory
        self.tenantId = tenantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case secretJson = "secret_json"
        case targetAudience = "target_audience"
        case appCategory = "app_category"
        case tenantId = "tenant_id"
    }

}
