//
// IntuneTargetAudience.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IntuneTargetAudience: Codable {

    /** display name for the target audience/group */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }

}
