//
// InvitationDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InvitationDetailResponse: Codable {

    /** The id of the invitation */
    public var invitationId: UUID
    public var invitedBy: InlineResponse20020
    public var organization: V01InvitationsSentOrganization?
    public var app: Any?

    public init(invitationId: UUID, invitedBy: InlineResponse20020, organization: V01InvitationsSentOrganization?, app: Any?) {
        self.invitationId = invitationId
        self.invitedBy = invitedBy
        self.organization = organization
        self.app = app
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case invitationId = "invitation_id"
        case invitedBy = "invited_by"
        case organization
        case app
    }

}
