//
// LegacyDeploymentMetricsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LegacyDeploymentMetricsResponse: Codable {

    /** Object containing a property named after each release label, which contains an object that contains that release&#39;s metrics. */
    public var metrics: [String:LegacyDeploymentMetricsResponseMetrics]?

    public init(metrics: [String:LegacyDeploymentMetricsResponseMetrics]?) {
        self.metrics = metrics
    }

}
