//
// LegacyCodePushReleaseInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LegacyCodePushReleaseInfo: Codable {

    public var appVersion: String?
    public var description: String?
    public var isDisabled: Bool?
    public var isMandatory: Bool?
    public var rollout: Int?

    public init(appVersion: String?, description: String?, isDisabled: Bool?, isMandatory: Bool?, rollout: Int?) {
        self.appVersion = appVersion
        self.description = description
        self.isDisabled = isDisabled
        self.isMandatory = isMandatory
        self.rollout = rollout
    }

}
