//
// LegacyCodePushReleaseModification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LegacyCodePushReleaseModification: Codable {

    /** The release package information */
    public var packageInfo: Any

    public init(packageInfo: Any) {
        self.packageInfo = packageInfo
    }

}
