//
// LegacyAppListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LegacyAppListResponse: Codable {

    public var apps: [LegacyAppListResponseApps]?

    public init(apps: [LegacyAppListResponseApps]?) {
        self.apps = apps
    }

}
