//
// LogFlowPageLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Page view log (as in screens or activities). */
public struct LogFlowPageLog: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case event = "event"
        case page = "page"
        case startSession = "start_session"
        case error = "error"
        case pushInstallation = "push_installation"
        case startService = "start_service"
        case customProperties = "custom_properties"
    }
    /** Session ID.  */
    public var sessionId: UUID?
    /** Name of the page.  */
    public var name: String?
    /** Log type.  */
    public var type: ModelType
    /** Log creation timestamp.  */
    public var timestamp: Date
    /** Install ID.  */
    public var installId: UUID
    /** Device characteristics. */
    public var device: Any

    public init(sessionId: UUID?, name: String?, type: ModelType, timestamp: Date, installId: UUID, device: Any) {
        self.sessionId = sessionId
        self.name = name
        self.type = type
        self.timestamp = timestamp
        self.installId = installId
        self.device = device
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case sessionId = "session_id"
        case name
        case type
        case timestamp
        case installId = "install_id"
        case device
    }

}
