//
// ManagementReleaseDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Details of an uploaded release */
public struct ManagementReleaseDetailsResponse: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case hockeyapp = "hockeyapp"
        case appcenter = "appcenter"
    }
    /** ID identifying this unique release. */
    public var distinctId: Int?
    /** The release&#39;s origin */
    public var origin: Origin?
    /** The release&#39;s short version.&lt;br&gt; For iOS: CFBundleShortVersionString from info.plist.&lt;br&gt; For Android: android:versionName from AppManifest.xml.  */
    public var version: String?
    /** The release&#39;s buildVersion.&lt;br&gt; For iOS: CFBundleVersion from info.plist.&lt;br&gt; For Android: android:versionCode from AppManifest.xml.  */
    public var buildVersion: String?
    /** The release&#39;s sortVersion. */
    public var sortVersion: String?
    /** UTC time the release was created in ISO 8601 format. */
    public var createdAt: String?
    /** This value determines the whether a release currently is enabled or disabled. */
    public var enabled: Bool?
    /** UTC time the release was created in ISO 8601 format. */
    public var deletedAt: String?

    public init(distinctId: Int?, origin: Origin?, version: String?, buildVersion: String?, sortVersion: String?, createdAt: String?, enabled: Bool?, deletedAt: String?) {
        self.distinctId = distinctId
        self.origin = origin
        self.version = version
        self.buildVersion = buildVersion
        self.sortVersion = sortVersion
        self.createdAt = createdAt
        self.enabled = enabled
        self.deletedAt = deletedAt
    }

}
