//
// MbaasSurveyDataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MbaasSurveyDataResponse: Codable {

    /** The next mbaas survey date for the user */
    public var nextSurveyDate: String?

    public init(nextSurveyDate: String?) {
        self.nextSurveyDate = nextSurveyDate
    }

}
