//
// Modules.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Modules: Codable {

    public var modules: [String:[String:Bool]]?

    public init(modules: [String:[String:Bool]]?) {
        self.modules = modules
    }

}
