//
// MSAUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** an MSA user&#39;s hex CID */
public struct MSAUser: Codable {

    /** the user&#39;s CID */
    public var hexcid: String

    public init(hexcid: String) {
        self.hexcid = hexcid
    }

}
