//
// NewAppReleaseAlertingEventAllOfAppReleaseProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Properties of new application release */
public struct NewAppReleaseAlertingEventAllOfAppReleaseProperties: Codable {

    public var appName: String
    public var appDisplayName: String
    public var releaseId: String
    public var platform: String
    /** Date and time in ISO 8601 format */
    public var uploadedAt: String
    public var fingerprint: String?
    public var releaseNotes: String?
    public var version: String
    public var shortVersion: String
    public var minOs: String?
    public var mandatoryUpdate: Bool?
    public var size: Int
    public var provisioningProfileName: String?
    public var provisioningProfileType: String?
    public var bundleIdentifier: String
    public var installLink: String
    public var iconLink: String?
    public var distributionGroupId: String?
    public var installable: Bool?

    public init(appName: String, appDisplayName: String, releaseId: String, platform: String, uploadedAt: String, fingerprint: String?, releaseNotes: String?, version: String, shortVersion: String, minOs: String?, mandatoryUpdate: Bool?, size: Int, provisioningProfileName: String?, provisioningProfileType: String?, bundleIdentifier: String, installLink: String, iconLink: String?, distributionGroupId: String?, installable: Bool?) {
        self.appName = appName
        self.appDisplayName = appDisplayName
        self.releaseId = releaseId
        self.platform = platform
        self.uploadedAt = uploadedAt
        self.fingerprint = fingerprint
        self.releaseNotes = releaseNotes
        self.version = version
        self.shortVersion = shortVersion
        self.minOs = minOs
        self.mandatoryUpdate = mandatoryUpdate
        self.size = size
        self.provisioningProfileName = provisioningProfileName
        self.provisioningProfileType = provisioningProfileType
        self.bundleIdentifier = bundleIdentifier
        self.installLink = installLink
        self.iconLink = iconLink
        self.distributionGroupId = distributionGroupId
        self.installable = installable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appName = "app_name"
        case appDisplayName = "app_display_name"
        case releaseId = "release_id"
        case platform
        case uploadedAt = "uploaded_at"
        case fingerprint
        case releaseNotes = "release_notes"
        case version
        case shortVersion = "short_version"
        case minOs = "min_os"
        case mandatoryUpdate = "mandatory_update"
        case size
        case provisioningProfileName = "provisioning_profile_name"
        case provisioningProfileType = "provisioning_profile_type"
        case bundleIdentifier = "bundle_identifier"
        case installLink = "install_link"
        case iconLink = "icon_link"
        case distributionGroupId = "distribution_group_id"
        case installable
    }

}
