//
// NewCrashGroupAlertingEventAllOf1CrashGroupProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Properties of new crash group */
public struct NewCrashGroupAlertingEventAllOf1CrashGroupProperties: Codable {

    public var id: String
    public var name: String
    public var reason: String
    public var url: String
    public var appDisplayName: String
    public var appPlatform: String
    public var appVersion: String
    public var stackTrace: [String]

    public init(id: String, name: String, reason: String, url: String, appDisplayName: String, appPlatform: String, appVersion: String, stackTrace: [String]) {
        self.id = id
        self.name = name
        self.reason = reason
        self.url = url
        self.appDisplayName = appDisplayName
        self.appPlatform = appPlatform
        self.appVersion = appVersion
        self.stackTrace = stackTrace
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case reason
        case url
        case appDisplayName = "app_display_name"
        case appPlatform = "app_platform"
        case appVersion = "app_version"
        case stackTrace = "stack_trace"
    }

}
