//
// NotificationConfigAppleToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Apple notification auth token configuration. The &#39;type&#39; property must be set to &#39;apns_token_config&#39;. */
public struct NotificationConfigAppleToken: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case apnsTokenConfig = "apns_token_config"
        case gcmConfig = "gcm_config"
        case wnsConfig = "wns_config"
    }
    public enum EndpointType: String, Codable, CaseIterable {
        case production = "production"
        case sandbox = "sandbox"
    }
    public var type: ModelType
    /** A 10-character key identifier (kid). */
    public var keyId: String?
    /** Application ID. */
    public var id: String?
    /** Application prefix. */
    public var _prefix: String?
    /** Provider Authentication Token. */
    public var token: String?
    /** Type of endpoint the certificate or token are associated with */
    public var endpointType: EndpointType?

    public init(type: ModelTypekeyId: String?, id: String?, _prefix: String?, token: String?, endpointType: EndpointType?) {
        self.type = type
        self.keyId = keyId
        self.id = id
        self._prefix = _prefix
        self.token = token
        self.endpointType = endpointType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case keyId = "key_id"
        case id
        case _prefix = "prefix"
        case token
        case endpointType = "endpoint_type"
    }

}
