//
// NotificationOverviewResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Notification statistics */
public struct NotificationOverviewResult: Codable {

    public enum State: String, Codable, CaseIterable {
        case queued = "Queued"
        case sending = "Sending"
        case completed = "Completed"
        case failed = "Failed"
        case noTargetFound = "NoTargetFound"
    }
    /** Notification id. */
    public var notificationId: String
    /** Notification name */
    public var name: String?
    public var notificationTarget: InlineResponse20035NotificationTarget?
    /** Notification send time */
    public var sendTime: Date?
    /** Number of the notifications failed to send to the push provider. */
    public var pnsSendFailure: Int?
    /** Number of the notifications successfully sent to push the provider. */
    public var pnsSendSuccess: Int?
    /** State of the notification. */
    public var state: State

    public init(notificationId: String, name: String?, notificationTarget: InlineResponse20035NotificationTarget?, sendTime: Date?, pnsSendFailure: Int?, pnsSendSuccess: Int?, state: State) {
        self.notificationId = notificationId
        self.name = name
        self.notificationTarget = notificationTarget
        self.sendTime = sendTime
        self.pnsSendFailure = pnsSendFailure
        self.pnsSendSuccess = pnsSendSuccess
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case notificationId = "notification_id"
        case name
        case notificationTarget = "notification_target"
        case sendTime = "send_time"
        case pnsSendFailure = "pns_send_failure"
        case pnsSendSuccess = "pns_send_success"
        case state
    }

}
