//
// NotificationConfigWindows.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** WNS notification configuration. The &#39;type&#39; property must be set to &#39;wns_config&#39; */
public struct NotificationConfigWindows: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case apnsTokenConfig = "apns_token_config"
        case gcmConfig = "gcm_config"
        case wnsConfig = "wns_config"
    }
    public var type: ModelType
    /** Package security identifier (SID). */
    public var packageSid: String?
    /** Secret key. */
    public var secretKey: String?

    public init(type: ModelTypepackageSid: String?, secretKey: String?) {
        self.type = type
        self.packageSid = packageSid
        self.secretKey = secretKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case packageSid = "package_sid"
        case secretKey = "secret_key"
    }

}
