//
// NotificationDefinition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Notification definition object */
public struct NotificationDefinition: Codable {

    public var notificationTarget: InlineResponse20035NotificationTarget?
    public var notificationContent: V01AppsOwnerNameAppNamePushNotificationsNotificationContent

    public init(notificationTarget: InlineResponse20035NotificationTarget?, notificationContent: V01AppsOwnerNameAppNamePushNotificationsNotificationContent) {
        self.notificationTarget = notificationTarget
        self.notificationContent = notificationContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case notificationTarget = "notification_target"
        case notificationContent = "notification_content"
    }

}
