//
// NotificationConfigAppleResultAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Generic notification configuration result. */
public struct NotificationConfigAppleResultAllOf: Codable {

    public var type: String

    public init(type: String) {
        self.type = type
    }

}
