//
// NotificationPlatformType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Notification platform type */
public enum NotificationPlatformType: String, Codable, CaseIterable {
    case apns = "apns"
    case gcm = "gcm"
    case wns = "wns"
}
