//
// NotificationFailureOutcomeCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Notification failure outcome count */
public struct NotificationFailureOutcomeCount: Codable {

    /** The reason of the notification failure */
    public var failureReason: String?
    /** count of this type of failure */
    public var count: Int64?

    public init(failureReason: String?, count: Int64?) {
        self.failureReason = failureReason
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case failureReason = "failure_reason"
        case count
    }

}
