//
// NotificationConfigGoogleResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Google notification configuration result. */
public struct NotificationConfigGoogleResult: Codable {

    public var type: String
    /** GCM API key. */
    public var googleApiKey: String?

    public init(type: StringgoogleApiKey: String?) {
        self.type = type
        self.googleApiKey = googleApiKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case googleApiKey = "google_api_key"
    }

}
