//
// OrganizationInvitationSimpleDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrganizationInvitationSimpleDetailResponse: Codable {

    /** The unique ID (UUID) of the invitation */
    public var id: UUID
    /** The email address of the invited user */
    public var email: String
    /** The role assigned to the invited user */
    public var role: String

    public init(id: UUID, email: String, role: String) {
        self.id = id
        self.email = email
        self.role = role
    }

}
