//
// OrganizationUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrganizationUserResponse: Codable {

    /** The email address of the user */
    public var email: String
    /** The full name of the user. Might for example be first and last name */
    public var displayName: String
    /** The date when the user joined the organization */
    public var joinedAt: String
    /** The unique name that is used to identify the user. */
    public var name: String
    /** The role the user has within the organization */
    public var role: String

    public init(email: String, displayName: String, joinedAt: String, name: String, role: String) {
        self.email = email
        self.displayName = displayName
        self.joinedAt = joinedAt
        self.name = name
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case email
        case displayName = "display_name"
        case joinedAt = "joined_at"
        case name
        case role
    }

}
