//
// OrganizationInvitationDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrganizationInvitationDetailResponse: Codable {

    /** The unique ID (UUID) of the invitation */
    public var id: UUID
    public var organization: V01InvitationsSentOrganization
    /** The email address of the invited user */
    public var email: String
    public var invitedBy: InlineResponse20020
    /** Indicates whether the invited user already exists */
    public var isExistingUser: Bool
    /** The role assigned to the invited user */
    public var role: String?

    public init(id: UUID, organization: V01InvitationsSentOrganization, email: String, invitedBy: InlineResponse20020, isExistingUser: Bool, role: String?) {
        self.id = id
        self.organization = organization
        self.email = email
        self.invitedBy = invitedBy
        self.isExistingUser = isExistingUser
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case organization
        case email
        case invitedBy = "invited_by"
        case isExistingUser = "is_existing_user"
        case role
    }

}
