//
// OrgComplianceSettingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** org settings response */
public struct OrgComplianceSettingsResponse: Codable {

    /** The internal unique id (UUID) of the organization compliance setting */
    public var id: String
    /** The internal unique id (UUID) of the organization. */
    public var orgId: String
    /** certificate connection id to wrap and resign the app after wrapping */
    public var certificateConnectionId: String
    /** flag to tell if mam warpping is enabled on the Org */
    public var isMamEnabled: Bool?

    public init(id: String, orgId: String, certificateConnectionId: String, isMamEnabled: Bool?) {
        self.id = id
        self.orgId = orgId
        self.certificateConnectionId = certificateConnectionId
        self.isMamEnabled = isMamEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case orgId = "org_id"
        case certificateConnectionId = "certificate_connection_id"
        case isMamEnabled = "is_mam_enabled"
    }

}
