//
// OrgDistributionGroupAppResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrgDistributionGroupAppResponseAllOf: Codable {

    /** The platform of the app */
    public var platform: String?
    /** The creation origin of this app */
    public var origin: String?

    public init(platform: String?, origin: String?) {
        self.platform = platform
        self.origin = origin
    }

}
