//
// OrgDistributionGroupDetailsResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrgDistributionGroupDetailsResponseAllOf: Codable {

    /** The count of apps associated with this distribution group */
    public var totalAppsCount: Double?
    /** The count of users in the distribution group */
    public var totalUsersCount: Double?
    /** The apps associated with the distribution group */
    public var apps: [Any]?

    public init(totalAppsCount: Double?, totalUsersCount: Double?, apps: [Any]?) {
        self.totalAppsCount = totalAppsCount
        self.totalUsersCount = totalUsersCount
        self.apps = apps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalAppsCount = "total_apps_count"
        case totalUsersCount = "total_users_count"
        case apps
    }

}
