//
// OSes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OSes: Codable {

    public var total: Int64?
    public var oses: [InlineResponse20084Oses]?

    public init(total: Int64?, oses: [InlineResponse20084Oses]?) {
        self.total = total
        self.oses = oses
    }

}
