//
// OverviewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OverviewResponse: Codable {

    public enum DatabaseLocation: String, Codable, CaseIterable {
        case eastAsia = "East Asia"
        case southeastAsia = "Southeast Asia"
        case australiaCentral = "Australia Central"
        case australiaCentral2 = "Australia Central 2"
        case australiaEast = "Australia East"
        case australiaSoutheast = "Australia Southeast"
        case brazilSouth = "Brazil South"
        case canadaCentral = "Canada Central"
        case canadaEast = "Canada East"
        case centralIndia = "Central India"
        case southIndia = "South India"
        case westIndia = "West India"
        case northEurope = "North Europe"
        case westEurope = "West Europe"
        case franceCentral = "France Central"
        case franceSouth = "France South"
        case germanyCentral = "Germany Central"
        case germanyNortheast = "Germany Northeast"
        case japanEast = "Japan East"
        case japanWest = "Japan West"
        case koreaCentral = "Korea Central"
        case koreaSouth = "Korea South"
        case southAfricaNorth = "South Africa North"
        case southAfricaWest = "South Africa West"
        case ukSouth = "UK South"
        case ukWest = "UK West"
        case centralUs = "Central US"
        case eastUs = "East US"
        case eastUs2 = "East US 2"
        case usGovArizona = "US Gov Arizona"
        case usGovTexas = "US Gov Texas"
        case northCentralUs = "North Central US"
        case southCentralUs = "South Central US"
        case westUs = "West US"
        case westUs2 = "West US 2"
        case westCentralUs = "West Central US"
    }
    public var databaseLocation: DatabaseLocation?
    public var accountName: String?
    public var databaseId: String?
    public var throughput: Int?

    public init(databaseLocation: DatabaseLocation?, accountName: String?, databaseId: String?, throughput: Int?) {
        self.databaseLocation = databaseLocation
        self.accountName = accountName
        self.databaseId = databaseId
        self.throughput = throughput
    }

}
