//
// PerformanceReportVideoVideoMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PerformanceReportVideoVideoMetadata: Codable {

    public var events: [PerformanceReportVideoVideoMetadataEvents]?

    public init(events: [PerformanceReportVideoVideoMetadataEvents]?) {
        self.events = events
    }

}
