//
// PerformanceReportPerformanceDataSteps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PerformanceReportPerformanceDataSteps: Codable {

    public var avgCpu: Double?
    public var avgMem: Double?
    public var samples: [PerformanceReportPerformanceDataSamples]?
    public var elapsedSecsEnd: Double?
    public var elapsedSecsStart: Double?
    public var elapsedSecs: Double?
    public var name: String?
    public var id: String?

    public init(avgCpu: Double?, avgMem: Double?, samples: [PerformanceReportPerformanceDataSamples]?, elapsedSecsEnd: Double?, elapsedSecsStart: Double?, elapsedSecs: Double?, name: String?, id: String?) {
        self.avgCpu = avgCpu
        self.avgMem = avgMem
        self.samples = samples
        self.elapsedSecsEnd = elapsedSecsEnd
        self.elapsedSecsStart = elapsedSecsStart
        self.elapsedSecs = elapsedSecs
        self.name = name
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case avgCpu = "avg-cpu"
        case avgMem = "avg-mem"
        case samples
        case elapsedSecsEnd = "elapsed-secs-end"
        case elapsedSecsStart = "elapsed-secs-start"
        case elapsedSecs = "elapsed-secs"
        case name
        case id
    }

}
