//
// PerformanceReportPerformanceData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PerformanceReportPerformanceData: Codable {

    public var steps: [PerformanceReportPerformanceDataSteps]
    public var elapsedSecsEnd: Double
    public var elapsedSecsStart: Double
    public var elapsedSecs: Double
    public var id: String

    public init(steps: [PerformanceReportPerformanceDataSteps], elapsedSecsEnd: Double, elapsedSecsStart: Double, elapsedSecs: Double, id: String) {
        self.steps = steps
        self.elapsedSecsEnd = elapsedSecsEnd
        self.elapsedSecsStart = elapsedSecsStart
        self.elapsedSecs = elapsedSecs
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case steps
        case elapsedSecsEnd = "elapsed-secs-end"
        case elapsedSecsStart = "elapsed-secs-start"
        case elapsedSecs = "elapsed-secs"
        case id
    }

}
