//
// PerformanceReportVideoVideoMetadataEvents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PerformanceReportVideoVideoMetadataEvents: Codable {

    public var id: String?
    public var millis: Double?
    public var name: String?
    public var type: String?

    public init(id: String?, millis: Double?, name: String?, type: String?) {
        self.id = id
        self.millis = millis
        self.name = name
        self.type = type
    }

}
