//
// PlacesPlaces.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The place code and the count. */
public struct PlacesPlaces: Codable {

    /** The place code. */
    public var code: String?
    /** The count of the this place. */
    public var count: Int64?
    /** The count of previous time range of the place. */
    public var previousCount: Int64?

    public init(code: String?, count: Int64?, previousCount: Int64?) {
        self.code = code
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case code
        case count
        case previousCount = "previous_count"
    }

}
