//
// PostExternalDownloadUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Set the download URL of an external build */
public struct PostExternalDownloadUrl: Codable {

    /** The new download URL */
    public var downloadUrl: String?

    public init(downloadUrl: String?) {
        self.downloadUrl = downloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case downloadUrl = "download_url"
    }

}
