//
// PrivateCreateStoreRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** create the store through private API. Used by UI. */
public struct PrivateCreateStoreRequest: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case intune = "intune"
    }
    /** store Type */
    public var type: ModelType?
    /** name of the store. */
    public var name: String?
    public var intuneDetails: PrivateCreateStoreRequestIntuneDetails?

    public init(type: ModelType?, name: String?, intuneDetails: PrivateCreateStoreRequestIntuneDetails?) {
        self.type = type
        self.name = name
        self.intuneDetails = intuneDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case name
        case intuneDetails = "intune_details"
    }

}
