//
// ProvisioningProfileMigration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Describes the migration schema for a provisioning profile defined in HockeyApp. */
public struct ProvisioningProfileMigration: Codable {

    /** The name of the provisioning profile. */
    public var name: String
    /** The bundle/application identifier. */
    public var bundleId: String
    /** The team identifier. */
    public var teamIdentifier: String
    /** The type of provisoning profile. */
    public var type: Int
    /** A boolean value that indicates whether the provisioning profile represents an app extension. */
    public var isAppex: Bool
    /** The provisioning profile&#39;s expiration date in RFC 3339 format, i.e. 2017-07-21T17:32:28Z. */
    public var expiredAt: Date?
    /** A list of UDIDs of provisioned devices. */
    public var udids: [String]?
    /** A provisioning profile URL that indicates where to download it from. */
    public var url: String?

    public init(name: String, bundleId: String, teamIdentifier: String, type: Int, isAppex: Bool, expiredAt: Date?, udids: [String]?, url: String?) {
        self.name = name
        self.bundleId = bundleId
        self.teamIdentifier = teamIdentifier
        self.type = type
        self.isAppex = isAppex
        self.expiredAt = expiredAt
        self.udids = udids
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case bundleId = "bundle_id"
        case teamIdentifier = "team_identifier"
        case type
        case isAppex = "is_appex"
        case expiredAt = "expired_at"
        case udids
        case url
    }

}
