//
// ProvisionStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ProvisionStatusResponse: Codable {

    public enum Status: String, Codable, CaseIterable {
        case empty = "Empty"
        case accepted = "Accepted"
        case creating = "Creating"
        case connected = "Connected"
        case invalid = "Invalid"
    }
    public var status: Status
    public var message: String?

    public init(status: Status, message: String?) {
        self.status = status
        self.message = message
    }

}
