//
// PublishDevicesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The publising information. */
public struct PublishDevicesRequest: Codable {

    /** The username for the Apple Developer account to publish the devices to. */
    public var username: String?
    /** The password for the Apple Developer account to publish the devices to. */
    public var password: String?
    /** The service_connection_id of the stored Apple credentials instead of username, password. */
    public var accountServiceConnectionId: String?
    /** When set to true, all unprovisioned devices will be published to the Apple Developer account.  When false, only the provided devices will be published to the Apple Developer account. */
    public var publishAllDevices: Bool?
    /** Array of device UDID&#39;s to be published to the Apple Developer account. */
    public var devices: [String]?

    public init(username: String?, password: String?, accountServiceConnectionId: String?, publishAllDevices: Bool?, devices: [String]?) {
        self.username = username
        self.password = password
        self.accountServiceConnectionId = accountServiceConnectionId
        self.publishAllDevices = publishAllDevices
        self.devices = devices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case username
        case password
        case accountServiceConnectionId = "account_service_connection_id"
        case publishAllDevices = "publish_all_devices"
        case devices
    }

}
