//
// PublishDevicesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The information for a single iOS device */
public struct PublishDevicesResponse: Codable {

    /** The file name for the provisioning profile. */
    public var profileFileName: String?
    /** The updated provisioning profiles zip base64 encoded. */
    public var profilesZipBase64: String

    public init(profileFileName: String?, profilesZipBase64: String) {
        self.profileFileName = profileFileName
        self.profilesZipBase64 = profilesZipBase64
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case profileFileName = "profile_file_name"
        case profilesZipBase64 = "profiles_zip_base64"
    }

}
