//
// PurgeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PurgeResponse: Codable {

    public var status: String

    public init(status: String) {
        self.status = status
    }

}
