//
// ReleaseUpdateError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseUpdateError: Codable {

    public enum Code: String, Codable, CaseIterable {
        case badRequest = "BadRequest"
        case conflict = "Conflict"
        case notAcceptable = "NotAcceptable"
        case notFound = "NotFound"
        case internalServerError = "InternalServerError"
        case unauthorized = "Unauthorized"
        case tooManyRequests = "TooManyRequests"
    }
    public var code: Code
    public var message: String
    public var releaseNotes: String?
    public var mandatoryUpdate: Bool?
    public var destinations: [InlineResponse400Destinations]?

    public init(code: Code, message: String, releaseNotes: String?, mandatoryUpdate: Bool?, destinations: [InlineResponse400Destinations]?) {
        self.code = code
        self.message = message
        self.releaseNotes = releaseNotes
        self.mandatoryUpdate = mandatoryUpdate
        self.destinations = destinations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case code
        case message
        case releaseNotes = "release_notes"
        case mandatoryUpdate = "mandatory_update"
        case destinations
    }

}
