//
// ReleaseDetailsUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for updating release details */
public struct ReleaseDetailsUpdateResponse: Codable {

    public var releaseNotes: String?

    public init(releaseNotes: String?) {
        self.releaseNotes = releaseNotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case releaseNotes = "release_notes"
    }

}
