//
// ReleaseDestinationRequestAllOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseDestinationRequestAllOf1: Codable {

    /** Flag to mark the release for the provided destinations as mandatory */
    public var mandatoryUpdate: Bool?
    /** Flag to enable or disable notifications to testers */
    public var notifyTesters: Bool? = true

    public init(mandatoryUpdate: Bool?, notifyTesters: Bool?) {
        self.mandatoryUpdate = mandatoryUpdate
        self.notifyTesters = notifyTesters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case mandatoryUpdate = "mandatory_update"
        case notifyTesters = "notify_testers"
    }

}
