//
// ReleaseRealTimeStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** status of the app from store */
public struct ReleaseRealTimeStatusResponse: Codable {

    /** release id */
    public var releaseId: String?
    /** app id */
    public var appId: String?
    public var status: ReleaseRealTimeStatusResponseStatus?

    public init(releaseId: String?, appId: String?, status: ReleaseRealTimeStatusResponseStatus?) {
        self.releaseId = releaseId
        self.appId = appId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case releaseId = "release_id"
        case appId = "app_id"
        case status
    }

}
