//
// ReleaseExternalUrlUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for updating release external url */
public struct ReleaseExternalUrlUpdateResponse: Codable {

    public var externalDownloadUrl: String?

    public init(externalDownloadUrl: String?) {
        self.externalDownloadUrl = externalDownloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case externalDownloadUrl = "external_download_url"
    }

}
