//
// Release.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Release: Codable {

    /** Release Id.  */
    public var release: String

    public init(release: String) {
        self.release = release
    }

}
