//
// ReleaseDestinationResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseDestinationResponseAllOf: Codable {

    /** Flag to mark the release for the provided destinations as mandatory */
    public var mandatoryUpdate: Bool
    /** The url to check provisioning status. */
    public var provisioningStatusUrl: String?

    public init(mandatoryUpdate: Bool, provisioningStatusUrl: String?) {
        self.mandatoryUpdate = mandatoryUpdate
        self.provisioningStatusUrl = provisioningStatusUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case mandatoryUpdate = "mandatory_update"
        case provisioningStatusUrl = "provisioning_status_url"
    }

}
