//
// ReleaseDestinationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseDestinationRequest: Codable {

    /** Unique id of the release destination */
    public var id: UUID
    /** Flag to mark the release for the provided destinations as mandatory */
    public var mandatoryUpdate: Bool?
    /** Flag to enable or disable notifications to testers */
    public var notifyTesters: Bool? = true

    public init(id: UUID, mandatoryUpdate: Bool?, notifyTesters: Bool?) {
        self.id = id
        self.mandatoryUpdate = mandatoryUpdate
        self.notifyTesters = notifyTesters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case mandatoryUpdate = "mandatory_update"
        case notifyTesters = "notify_testers"
    }

}
