//
// ReleaseProvisionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for provisioning a release */
public struct ReleaseProvisionResponse: Codable {

    /** The url to check provisioning status. */
    public var statusUrl: String?

    public init(statusUrl: String?) {
        self.statusUrl = statusUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case statusUrl = "status_url"
    }

}
