//
// ReleaseUploadEndResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A response containing information about the uploaded release. */
public struct ReleaseUploadEndResponse: Codable {

    /** The ID of the release. */
    public var releaseId: Double?
    /** A URL to the new release. If upload was aborted will be null. */
    public var releaseUrl: String?

    public init(releaseId: Double?, releaseUrl: String?) {
        self.releaseId = releaseId
        self.releaseUrl = releaseUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case releaseId = "release_id"
        case releaseUrl = "release_url"
    }

}
