//
// ReleaseTesterDestinationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseTesterDestinationRequest: Codable {

    /** Flag to mark the release for the provided destinations as mandatory */
    public var mandatoryUpdate: Bool?
    /** Tester&#39;s email address */
    public var email: String
    /** Flag to enable or disable notifications to testers */
    public var notifyTesters: Bool? = true

    public init(mandatoryUpdate: Bool?, email: String, notifyTesters: Bool?) {
        self.mandatoryUpdate = mandatoryUpdate
        self.email = email
        self.notifyTesters = notifyTesters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case mandatoryUpdate = "mandatory_update"
        case email
        case notifyTesters = "notify_testers"
    }

}
