//
// RepoConfigPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RepoConfigPostRequest: Codable {

    /** The GitHub App Installation id. Required for repositories connected from GitHub App */
    public var installationId: String?
    /** The repository&#39;s git url, must be a HTTPS URL */
    public var repoUrl: String?
    /** The repository id from the repository provider. Required for repositories connected from GitHub App and GitLab.com */
    public var repoId: String?
    /** The external user id from the repository provider. Required for GitLab.com repositories */
    public var externalUserId: String?
    /** The id of the service connection (private). Required for GitLab self-hosted repositories */
    public var serviceConnectionId: String?

    public init(installationId: String?repoUrl: String?, repoId: String?, externalUserId: String?, serviceConnectionId: String?) {
        self.installationId = installationId
        self.repoUrl = repoUrl
        self.repoId = repoId
        self.externalUserId = externalUserId
        self.serviceConnectionId = serviceConnectionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case installationId = "installation_id"
        case repoUrl = "repo_url"
        case repoId = "repo_id"
        case externalUserId = "external_user_id"
        case serviceConnectionId = "service_connection_id"
    }

}
