//
// RepoInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RepoInfo: Codable {

    /** The repository url */
    public var repoUrl: String
    /** The external user ID */
    public var externalUserId: String?

    public init(repoUrl: String, externalUserId: String?) {
        self.repoUrl = repoUrl
        self.externalUserId = externalUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case repoUrl = "repo_url"
        case externalUserId = "external_user_id"
    }

}
