//
// ResignAttemptResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** URL that can be used to check the status of the update devices operation and the updated profiles. */
public struct ResignAttemptResponse: Codable {

    /** The status of the resigning operation. */
    public var status: String
    /** ID of the user performing the resign operaiton. */
    public var userId: String
    /** App ID that the resign operation is being performed against. */
    public var appId: String
    /** ID of the release which is being resigned. */
    public var originalReleaseId: Double
    /** ID of the resign operation. */
    public var resignId: String
    /** Context ID for the resigning operation. */
    public var contextId: String
    /** The time that the resign operation was started. */
    public var startTime: Double
    /** List of destinations that the resign operation is being performed against. */
    public var destinations: [Any]?
    /** Error code associated with the exception. */
    public var errorCode: String?
    /** Error message associated with the exception. */
    public var errorMessage: String?

    public init(status: String, userId: String, appId: String, originalReleaseId: Double, resignId: String, contextId: String, startTime: Double, destinations: [Any]?, errorCode: String?, errorMessage: String?) {
        self.status = status
        self.userId = userId
        self.appId = appId
        self.originalReleaseId = originalReleaseId
        self.resignId = resignId
        self.contextId = contextId
        self.startTime = startTime
        self.destinations = destinations
        self.errorCode = errorCode
        self.errorMessage = errorMessage
    }

}
