//
// SecretDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SecretDetails: Codable {

    /** the id token of user */
    public var idToken: String?
    /** the refresh token for user */
    public var refreshToken: String?
    /** the expiry of refresh token */
    public var refreshTokenExpiry: String?

    public init(idToken: String?, refreshToken: String?, refreshTokenExpiry: String?) {
        self.idToken = idToken
        self.refreshToken = refreshToken
        self.refreshTokenExpiry = refreshTokenExpiry
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case idToken = "id_token"
        case refreshToken = "refresh_token"
        case refreshTokenExpiry = "refresh_token_expiry"
    }

}
