//
// SessionsPerDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SessionsPerDevice: Codable {

    /** Average seesion per user. */
    public var averageSessionsPerUser: Double?
    /** Previous average session per user. */
    public var previousAverageSessionsPerUser: Double?
    /** Total session per device count. */
    public var totalCount: Int64?
    /** Previous total count. */
    public var previousTotalCount: Int64?
    /** The session count for each interval per device. */
    public var sessionsPerUser: [InlineResponse20081SessionsPerUser]?

    public init(averageSessionsPerUser: Double?, previousAverageSessionsPerUser: Double?, totalCount: Int64?, previousTotalCount: Int64?, sessionsPerUser: [InlineResponse20081SessionsPerUser]?) {
        self.averageSessionsPerUser = averageSessionsPerUser
        self.previousAverageSessionsPerUser = previousAverageSessionsPerUser
        self.totalCount = totalCount
        self.previousTotalCount = previousTotalCount
        self.sessionsPerUser = sessionsPerUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case averageSessionsPerUser = "average_sessions_per_user"
        case previousAverageSessionsPerUser = "previous_average_sessions_per_user"
        case totalCount = "total_count"
        case previousTotalCount = "previous_total_count"
        case sessionsPerUser = "sessions_per_user"
    }

}
