//
// SharedConnectionPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Shared connection patch request */
public struct SharedConnectionPatchRequest: Codable {

    /** Display name of the shared connection */
    public var displayName: String?
    /** Represents the data for connecting to service */
    public var data: Any

    public init(displayName: String?, data: Any) {
        self.displayName = displayName
        self.data = data
    }

}
