//
// StepReportDeviceScreenshots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct StepReportDeviceScreenshots: Codable {

    public var id: String?
    public var deviceSnapshotId: String?
    public var stacktrace: [String]?
    public var crashData: [String]?
    public var status: String?
    public var title: String?
    public var screenshot: StepReportScreenshot?
    public var logFile: String?
    public var appiumLogFile: String?
    public var rawCrashData: [String]?

    public init(id: String?, deviceSnapshotId: String?, stacktrace: [String]?, crashData: [String]?, status: String?, title: String?, screenshot: StepReportScreenshot?, logFile: String?, appiumLogFile: String?, rawCrashData: [String]?) {
        self.id = id
        self.deviceSnapshotId = deviceSnapshotId
        self.stacktrace = stacktrace
        self.crashData = crashData
        self.status = status
        self.title = title
        self.screenshot = screenshot
        self.logFile = logFile
        self.appiumLogFile = appiumLogFile
        self.rawCrashData = rawCrashData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case deviceSnapshotId = "device_snapshot_id"
        case stacktrace
        case crashData = "crash_data"
        case status
        case title
        case screenshot
        case logFile = "log_file"
        case appiumLogFile = "appium_log_file"
        case rawCrashData = "raw_crash_data"
    }

}
