//
// StoreNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct StoreNotification: Codable {

    public var service: String?
    public var status: String?
    public var validUntil: Int?

    public init(service: String?, status: String?, validUntil: Int?) {
        self.service = service
        self.status = status
        self.validUntil = validUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case service
        case status
        case validUntil = "valid_until"
    }

}
