//
// StoresDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct StoresDetails: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case googleplay = "googleplay"
        case intune = "intune"
        case apple = "apple"
    }
    /** ID identifying a unique distribution store. */
    public var id: String?
    /** A name identifying a unique distribution store. */
    public var name: String?
    /** A type identifying the type of distribution store. */
    public var type: ModelType?
    /** A status identifying the status of release in the distribution store. */
    public var publishingStatus: String?
    /** Is the containing release the latest one in this distribution store. */
    public var isLatest: Bool?

    public init(id: String?, name: String?, type: ModelType?, publishingStatus: String?, isLatest: Bool?) {
        self.id = id
        self.name = name
        self.type = type
        self.publishingStatus = publishingStatus
        self.isLatest = isLatest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case type
        case publishingStatus = "publishing_status"
        case isLatest = "is_latest"
    }

}
