//
// StoresBasicDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct StoresBasicDetails: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case intune = "intune"
        case googleplay = "googleplay"
    }
    /** ID identifying a unique distribution store. */
    public var id: String?
    /** A name identifying a unique distribution store. */
    public var name: String?
    /** type of the distribution store currently stores type can be intune or googleplay. */
    public var type: ModelType?
    /** publishing status of the release in the store. */
    public var publishingStatus: String?

    public init(id: String?, name: String?, type: ModelType?, publishingStatus: String?) {
        self.id = id
        self.name = name
        self.type = type
        self.publishingStatus = publishingStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case type
        case publishingStatus = "publishing_status"
    }

}
