//
// StoreSecretResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** StoreSecretResponse */
public struct StoreSecretResponse: Codable {

    /** Store id */
    public var id: String?
    /** Store Name */
    public var name: String?
    /** Store Type */
    public var type: String?
    /** Secret Json */
    public var secret: String?
    /** Tenant Id for Intune */
    public var tenantId: String?

    public init(id: String?, name: String?, type: String?, secret: String?, tenantId: String?) {
        self.id = id
        self.name = name
        self.type = type
        self.secret = secret
        self.tenantId = tenantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case type
        case secret
        case tenantId = "tenant_id"
    }

}
