//
// SubscriptionMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SubscriptionMetrics: Codable {

    /** The name of the subsciption (prefixed with the topic name) */
    public var name: String
    /** The number of messages in the subscription */
    public var messageCount: Double

    public init(name: String, messageCount: Double) {
        self.name = name
        self.messageCount = messageCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case messageCount = "message_count"
    }

}
