//
// SymbolStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A response containing information pertaining to a symbol status */
public struct SymbolStatusResponse: Codable {

    public enum Status: String, Codable, CaseIterable {
        case available = "available"
        case ignored = "ignored"
        case missing = "missing"
    }
    /** The unique id for this symbol (uuid) */
    public var symbolId: String
    /** The application that this symbol belongs to */
    public var appId: String
    /** Whether the symbol is ignored. */
    public var status: Status

    public init(symbolId: String, appId: String, status: Status) {
        self.symbolId = symbolId
        self.appId = appId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case symbolId = "symbol_id"
        case appId = "app_id"
        case status
    }

}
