//
// SymbolLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Location for downloading symbol */
public struct SymbolLocation: Codable {

    public var uri: String

    public init(uri: String) {
        self.uri = uri
    }

}
