//
// SymbolUploadBeginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A response containing information pertaining to starting a symbol upload process */
public struct SymbolUploadBeginResponse: Codable {

    /** The id for the current upload */
    public var symbolUploadId: String
    /** The URL where the client needs to upload the symbol blob to */
    public var uploadUrl: String
    /** Describes how long the upload_url is valid */
    public var expirationDate: Date

    public init(symbolUploadId: String, uploadUrl: String, expirationDate: Date) {
        self.symbolUploadId = symbolUploadId
        self.uploadUrl = uploadUrl
        self.expirationDate = expirationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case symbolUploadId = "symbol_upload_id"
        case uploadUrl = "upload_url"
        case expirationDate = "expiration_date"
    }

}
