//
// SymbolUploadLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Location for downloading symbol upload */
public struct SymbolUploadLocation: Codable {

    public var uri: String

    public init(uri: String) {
        self.uri = uri
    }

}
