//
// TeamResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TeamResponse: Codable {

    /** The internal unique id (UUID) of the team. */
    public var id: UUID
    /** The name of the team */
    public var name: String
    /** The display name of the team */
    public var displayName: String
    /** The description of the team */
    public var description: String?

    public init(id: UUID, name: String, displayName: String, description: String?) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case displayName = "display_name"
        case description
    }

}
