//
// TeamAppResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TeamAppResponse: Codable {

    public enum Permissions: String, Codable, CaseIterable {
        case manager = "manager"
        case developer = "developer"
        case viewer = "viewer"
        case tester = "tester"
    }
    /** The internal unique id (UUID) of the team. */
    public var id: UUID
    /** The name of the team */
    public var name: String
    /** The display name of the team */
    public var displayName: String
    /** The description of the team */
    public var description: String?
    /** The permissions the team has for the app */
    public var permissions: [Permissions]?

    public init(id: UUID, name: String, displayName: String, description: String?, permissions: [Permissions]?) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.description = description
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case displayName = "display_name"
        case description
        case permissions
    }

}
