//
// TestRunStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Summary single test run on Xamarin Test Cloud */
public struct TestRunStatistics: Codable {

    /** Number of devices running the test */
    public var devices: Double?
    /** Number of finished devices */
    public var devicesFinished: Double?
    /** Number of failed devices */
    public var devicesFailed: Double?
    /** Number of tests in total */
    public var total: Double?
    /** Number of passed tests */
    public var passed: Double?
    /** Number of failed tests */
    public var failed: Double?
    /** Number of skipped tests */
    public var skipped: Double?
    /** The max amount of MB used during the test run */
    public var peakMemory: Double?
    /** The number of minutes of device time the test has been runnign */
    public var totalDeviceMinutes: Double?

    public init(devices: Double?, devicesFinished: Double?, devicesFailed: Double?, total: Double?, passed: Double?, failed: Double?, skipped: Double?, peakMemory: Double?, totalDeviceMinutes: Double?) {
        self.devices = devices
        self.devicesFinished = devicesFinished
        self.devicesFailed = devicesFailed
        self.total = total
        self.passed = passed
        self.failed = failed
        self.skipped = skipped
        self.peakMemory = peakMemory
        self.totalDeviceMinutes = totalDeviceMinutes
    }

}
