//
// TestCloudProjectFrameworkProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestCloudProjectFrameworkProperties: Codable {

    public var configurations: [String]?

    public init(configurations: [String]?) {
        self.configurations = configurations
    }

}
