//
// TestGDPRFeatureFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestGDPRFeatureFlag: Codable {

    public var name: String?
    public var targetId: UUID?

    public init(name: String?, targetId: UUID?) {
        self.name = name
        self.targetId = targetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case targetId = "target_id"
    }

}
