//
// TestReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestReport: Codable {

    public var appUploadId: String
    public var date: String
    public var testType: String
    public var platform: String
    public var stats: TestReportStats
    public var id: String
    public var schemaVersion: Double
    public var revision: Double
    public var features: [TestReportFeatures]
    public var finishedDeviceSnapshots: [String]
    public var deviceLogs: [TestReportDeviceLogs]
    public var dateFinished: String
    public var errorMessage: String?
    public var snapshotFatalErrors: [TestReportSnapshotFatalErrors]?

    public init(appUploadId: String, date: String, testType: String, platform: String, stats: TestReportStats, id: String, schemaVersion: Double, revision: Double, features: [TestReportFeatures], finishedDeviceSnapshots: [String], deviceLogs: [TestReportDeviceLogs], dateFinished: String, errorMessage: String?, snapshotFatalErrors: [TestReportSnapshotFatalErrors]?) {
        self.appUploadId = appUploadId
        self.date = date
        self.testType = testType
        self.platform = platform
        self.stats = stats
        self.id = id
        self.schemaVersion = schemaVersion
        self.revision = revision
        self.features = features
        self.finishedDeviceSnapshots = finishedDeviceSnapshots
        self.deviceLogs = deviceLogs
        self.dateFinished = dateFinished
        self.errorMessage = errorMessage
        self.snapshotFatalErrors = snapshotFatalErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appUploadId = "app_upload_id"
        case date
        case testType
        case platform
        case stats
        case id
        case schemaVersion = "schema_version"
        case revision
        case features
        case finishedDeviceSnapshots = "finished_device_snapshots"
        case deviceLogs = "device_logs"
        case dateFinished = "date_finished"
        case errorMessage
        case snapshotFatalErrors = "snapshot_fatal_errors"
    }

}
