//
// TesterAppResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TesterAppResponseAllOf: Codable {

    public enum Permissions: String, Codable, CaseIterable {
        case canRemoveFromApp = "can_remove_from_app"
    }
    /** it indicates if the app is microsoft internal */
    public var microsoftInternal: Bool?
    /** The permissions associated with the app */
    public var permissions: [Permissions]?

    public init(microsoftInternal: Bool?, permissions: [Permissions]?) {
        self.microsoftInternal = microsoftInternal
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case microsoftInternal = "microsoft_internal"
        case permissions
    }

}
