//
// TestCloudToolsetProjects.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestCloudToolsetProjects: Codable {

    public enum FrameworkType: String, Codable, CaseIterable {
        case appium = "Appium"
        case calabash = "Calabash"
        case espresso = "Espresso"
        case uitest = "UITest"
        case generated = "Generated"
    }
    /** The path to the TestCloud project */
    public var path: String
    public var frameworkType: FrameworkType
    public var frameworkProperties: TestCloudToolsetFrameworkProperties?

    public init(path: String, frameworkType: FrameworkType, frameworkProperties: TestCloudToolsetFrameworkProperties?) {
        self.path = path
        self.frameworkType = frameworkType
        self.frameworkProperties = frameworkProperties
    }

}
