//
// TestReportFeatures.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestReportFeatures: Codable {

    public var name: String?
    public var tests: [TestReportTests]?
    public var failed: Double?
    public var skipped: Double?
    public var peakMemory: Double?
    public var peakDuration: Double?

    public init(name: String?, tests: [TestReportTests]?, failed: Double?, skipped: Double?, peakMemory: Double?, peakDuration: Double?) {
        self.name = name
        self.tests = tests
        self.failed = failed
        self.skipped = skipped
        self.peakMemory = peakMemory
        self.peakDuration = peakDuration
    }

}
