//
// TestReportStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestReportStats: Codable {

    public var os: Double
    public var devices: Double
    public var filesize: Double
    public var totalDeviceMinutes: Double
    public var devicesNotRunned: Double
    public var failed: Double
    public var skipped: Double
    public var passed: Double
    public var total: Double
    public var devicesFinished: Double
    public var devicesFailed: Double
    public var devicesSkipped: Double
    public var stepCount: Double
    public var artifacts: [String:String]?

    public init(os: Double, devices: Double, filesize: Double, totalDeviceMinutes: Double, devicesNotRunned: Double, failed: Double, skipped: Double, passed: Double, total: Double, devicesFinished: Double, devicesFailed: Double, devicesSkipped: Double, stepCount: Double, artifacts: [String:String]?) {
        self.os = os
        self.devices = devices
        self.filesize = filesize
        self.totalDeviceMinutes = totalDeviceMinutes
        self.devicesNotRunned = devicesNotRunned
        self.failed = failed
        self.skipped = skipped
        self.passed = passed
        self.total = total
        self.devicesFinished = devicesFinished
        self.devicesFailed = devicesFailed
        self.devicesSkipped = devicesSkipped
        self.stepCount = stepCount
        self.artifacts = artifacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case os
        case devices
        case filesize
        case totalDeviceMinutes
        case devicesNotRunned = "devices_not_runned"
        case failed
        case skipped
        case passed
        case total
        case devicesFinished = "devices_finished"
        case devicesFailed = "devices_failed"
        case devicesSkipped = "devices_skipped"
        case stepCount = "step_count"
        case artifacts
    }

}
