//
// TestGDPRHashFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestGDPRHashFile: Codable {

    public var id: UUID?
    public var filename: String?

    public init(id: UUID?, filename: String?) {
        self.id = id
        self.filename = filename
    }

}
