//
// TestGDPRApp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestGDPRApp: Codable {

    public var hashFilesUrl: String?

    public init(hashFilesUrl: String?) {
        self.hashFilesUrl = hashFilesUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case hashFilesUrl = "hash_files_url"
    }

}
