//
// TestSeriesName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestSeriesName: Codable {

    /** Name of the new test series */
    public var name: String

    public init(name: String) {
        self.name = name
    }

}
