//
// TestCloudTestRunStartResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of starting a test run */
public struct TestCloudTestRunStartResult: Codable {

    /** List with names of accepted devices */
    public var acceptedDevices: [String]?
    /** List with names and descriptions of rejected devices */
    public var rejectedDevices: [String]?

    public init(acceptedDevices: [String]?, rejectedDevices: [String]?) {
        self.acceptedDevices = acceptedDevices
        self.rejectedDevices = rejectedDevices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case acceptedDevices = "accepted_devices"
        case rejectedDevices = "rejected_devices"
    }

}
