//
// Tier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Tier: Codable {

    /** The name of the tier */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }

}
