//
// TokenQueryResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Token query result. */
public struct TokenQueryResult: Codable {

    /** List of tokens. */
    public var tokens: [String]?

    public init(tokens: [String]?) {
        self.tokens = tokens
    }

}
