//
// ToolsetProjectsUwp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ToolsetProjectsUwp: Codable {

    /** The UWP solutions detected */
    public var uwpSolutions: [UWPToolsetUwpSolutions]

    public init(uwpSolutions: [UWPToolsetUwpSolutions]) {
        self.uwpSolutions = uwpSolutions
    }

}
