//
// ToolsetProjectsTestcloud.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ToolsetProjectsTestcloud: Codable {

    /** The TestCloud projects detected */
    public var projects: [TestCloudToolsetProjects]

    public init(projects: [TestCloudToolsetProjects]) {
        self.projects = projects
    }

}
