//
// Toolsets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Set of toolsets available for app */
public struct Toolsets: Codable {

    /** A list of Xamarin SDK bundles */
    public var xamarin: [InlineResponse20018]?
    /** A list of Xcode versions */
    public var xcode: [InlineResponse20017]?
    /** A list of Node versions */
    public var node: [InlineResponse20021Node]?

    public init(xamarin: [InlineResponse20018]?, xcode: [InlineResponse20017]?, node: [InlineResponse20021Node]?) {
        self.xamarin = xamarin
        self.xcode = xcode
        self.node = node
    }

}
