//
// ToolsetProjectsXamarin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ToolsetProjectsXamarin: Codable {

    /** Xamarin solutions for the toolset */
    public var xamarinSolutions: [XamarinToolsetXamarinSolutions]

    public init(xamarinSolutions: [XamarinToolsetXamarinSolutions]) {
        self.xamarinSolutions = xamarinSolutions
    }

}
