//
// TrustFrameworkPolicyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TrustFrameworkPolicyResponse: Codable {

    public var id: String?

    public init(id: String?) {
        self.id = id
    }

}
