//
// TrustFrameworkPoliciesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TrustFrameworkPoliciesResponse: Codable {

    public var value: [TrustFrameworkPoliciesResponseValue]?

    public init(value: [TrustFrameworkPoliciesResponseValue]?) {
        self.value = value
    }

}
