//
// UpdateResignStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Updates the status of the resign request */
public struct UpdateResignStatusRequest: Codable {

    /** The updated status for the resigning request. */
    public var status: String
    /** Error code if an error occured in the resigning operation. */
    public var errorCode: String?
    /** Error message if an error occured in the resigning operation. */
    public var errorMessage: String?

    public init(status: String, errorCode: String?, errorMessage: String?) {
        self.status = status
        self.errorCode = errorCode
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case status
        case errorCode = "error_code"
        case errorMessage = "error_message"
    }

}
