//
// UpdateCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UpdateCheckResponse: Codable {

    public var updateInfo: Any

    public init(updateInfo: Any) {
        self.updateInfo = updateInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case updateInfo = "update_info"
    }

}
