//
// UpdateInfoData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UpdateInfoData: Codable {

    public var targetBinaryRange: String?
    public var description: String?
    public var isDisabled: Bool?
    public var isMandatory: Bool?
    public var rollout: Int?
    public var downloadUrl: String?
    public var isAvailable: Bool?
    public var packageSize: Double?
    public var shouldRunBinaryVersion: Bool?
    public var updateAppVersion: Bool?
    public var packageHash: String?
    public var label: String?

    public init(targetBinaryRange: String?, description: String?, isDisabled: Bool?, isMandatory: Bool?, rollout: Int?, downloadUrl: String?, isAvailable: Bool?, packageSize: Double?, shouldRunBinaryVersion: Bool?, updateAppVersion: Bool?, packageHash: String?, label: String?) {
        self.targetBinaryRange = targetBinaryRange
        self.description = description
        self.isDisabled = isDisabled
        self.isMandatory = isMandatory
        self.rollout = rollout
        self.downloadUrl = downloadUrl
        self.isAvailable = isAvailable
        self.packageSize = packageSize
        self.shouldRunBinaryVersion = shouldRunBinaryVersion
        self.updateAppVersion = updateAppVersion
        self.packageHash = packageHash
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case targetBinaryRange = "target_binary_range"
        case description
        case isDisabled = "is_disabled"
        case isMandatory = "is_mandatory"
        case rollout
        case downloadUrl = "download_url"
        case isAvailable = "is_available"
        case packageSize = "package_size"
        case shouldRunBinaryVersion = "should_run_binary_version"
        case updateAppVersion = "update_app_version"
        case packageHash = "package_hash"
        case label
    }

}
