//
// UserInteractionMetricsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for retrieving user interaction metrics. */
public struct UserInteractionMetricsResponse: Codable {

    /** check if the user has less than 100 apps. */
    public var lessThan100Apps: Bool?
    /** check if the user&#39;s whole apps has more than 1 releases. */
    public var hasMoreThan1Release: Bool?

    public init(lessThan100Apps: Bool?, hasMoreThan1Release: Bool?) {
        self.lessThan100Apps = lessThan100Apps
        self.hasMoreThan1Release = hasMoreThan1Release
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case lessThan100Apps = "less_than_100_apps"
        case hasMoreThan1Release = "has_more_than_1_release"
    }

}
