//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserResponse: Codable {

    public var accountId: UUID
    public var mail: String?
    public var displayName: String

    public init(accountId: UUID, mail: String?, displayName: String) {
        self.accountId = accountId
        self.mail = mail
        self.displayName = displayName
    }

}
