//
// UserProfileResponseManagementAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserProfileResponseManagementAllOf: Codable {

    /** The date when the app was last updated */
    public var updatedAt: String?
    /** A boolean flag that indicates if the user is already verified */
    public var verified: Bool?
    /** The identity providers associated with the user&#39;s account */
    public var identityProviders: [UserProfileResponseManagementAllOfIdentityProviders]?

    public init(updatedAt: String?, verified: Bool?, identityProviders: [UserProfileResponseManagementAllOfIdentityProviders]?) {
        self.updatedAt = updatedAt
        self.verified = verified
        self.identityProviders = identityProviders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case updatedAt = "updated_at"
        case verified
        case identityProviders = "identity_providers"
    }

}
