//
// UserProfileResponseInternalAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserProfileResponseInternalAllOf: Codable {

    public enum AdminRole: String, Codable, CaseIterable {
        case superadmin = "superAdmin"
        case admin = "admin"
        case devops = "devOps"
        case customersupport = "customerSupport"
        case notadmin = "notAdmin"
    }
    /** The feature flags that are enabled for this app */
    public var featureFlags: [String]?
    /** The new admin_role */
    public var adminRole: AdminRole?
    public var settings: UserProfileResponseInternalAllOfSettings?

    public init(featureFlags: [String]?, adminRole: AdminRole?, settings: UserProfileResponseInternalAllOfSettings?) {
        self.featureFlags = featureFlags
        self.adminRole = adminRole
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case featureFlags = "feature_flags"
        case adminRole = "admin_role"
        case settings
    }

}
