//
// UserAuthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserAuthResponse: Codable {

    public enum Origin: String, Codable, CaseIterable {
        case appcenter = "appcenter"
        case hockeyapp = "hockeyapp"
        case codepush = "codepush"
    }
    /** The unique id (UUID) of the user */
    public var id: UUID
    /** The full name of the user. Might for example be first and last name */
    public var displayName: String
    /** The email address of the user */
    public var email: String
    /** The name of the external auth provider */
    public var externalProvider: String?
    /** The user ID given by the external provider */
    public var externalUserId: String?
    /** The unique name that is used to identify the user */
    public var name: String
    /** The creation origin of this user */
    public var origin: Origin

    public init(id: UUID, displayName: String, email: String, externalProvider: String?, externalUserId: String?, name: String, origin: Origin) {
        self.id = id
        self.displayName = displayName
        self.email = email
        self.externalProvider = externalProvider
        self.externalUserId = externalUserId
        self.name = name
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case displayName = "display_name"
        case email
        case externalProvider = "external_provider"
        case externalUserId = "external_user_id"
        case name
        case origin
    }

}
