//
// V01AppsOwnerNameAppNameDeviceConfigurationsModelMemory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Memory data for device */
public struct V01AppsOwnerNameAppNameDeviceConfigurationsModelMemory: Codable {

    public var formattedSize: String?

    public init(formattedSize: String?) {
        self.formattedSize = formattedSize
    }

}
