//
// V01AppsOwnerNameAppNameDeviceConfigurationsImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V01AppsOwnerNameAppNameDeviceConfigurationsImage: Codable {

    public var full: String?
    public var thumb: String?

    public init(full: String?, thumb: String?) {
        self.full = full
        self.thumb = thumb
    }

}
