//
// V01AppsOwnerNameAppNameDeviceConfigurationsModelCpu.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** CPU data for device */
public struct V01AppsOwnerNameAppNameDeviceConfigurationsModelCpu: Codable {

    public var frequency: String?
    public var core: String?
    public var text: String?

    public init(frequency: String?, core: String?, text: String?) {
        self.frequency = frequency
        self.core = core
        self.text = text
    }

}
