//
// V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsApps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V01OrgsOrgNameDistributionGroupsDistributionGroupNameAppsApps: Codable {

    /** The name of the app to be added to the distribution group */
    public var name: String

    public init(name: String) {
        self.name = name
    }

}
