//
// V2FailureResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** failure response object */
public struct V2FailureResponse: Codable {

    public var code: String
    public var message: String

    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }

}
