//
// V2MissingSymbolCrashGroupsInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** missing symbol groups */
public struct V2MissingSymbolCrashGroupsInfoResponse: Codable {

    /** total number of crashes for all missing symbol groups */
    public var totalCrashCount: Int

    public init(totalCrashCount: Int) {
        self.totalCrashCount = totalCrashCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCrashCount = "total_crash_count"
    }

}
