//
// V2MissingSymbolCrashGroupsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** grouped by missing symbols crashes response object */
public struct V2MissingSymbolCrashGroupsResponse: Codable {

    /** total number of crashes for all the groups */
    public var totalCrashCount: Int
    /** list of crash groups formed by missing symbols combination */
    public var groups: [V2MissingSymbolCrashGroupsResponseGroups]

    public init(totalCrashCount: Int, groups: [V2MissingSymbolCrashGroupsResponseGroups]) {
        self.totalCrashCount = totalCrashCount
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCrashCount = "total_crash_count"
        case groups
    }

}
