//
// V2StatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** status response object */
public struct V2StatusResponse: Codable {

    public var status: String

    public init(status: String) {
        self.status = status
    }

}
