//
// V2SymbolUpdateInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** symbol update message */
public struct V2SymbolUpdateInfo: Codable {

    public enum Status: String, Codable, CaseIterable {
        case missing = "missing"
        case ignored = "ignored"
        case available = "available"
    }
    /** UUID of the symbol */
    public var symbolId: String
    /** application id */
    public var appId: String
    /** symbol upload status */
    public var status: Status

    public init(symbolId: String, appId: String, status: Status) {
        self.symbolId = symbolId
        self.appId = appId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case symbolId = "symbol_id"
        case appId = "app_id"
        case status
    }

}
