//
// VersionDiagnostics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VersionDiagnostics: Codable {

    /** version */
    public var version: String?
    /** version count */
    public var count: Int64?
    /** the count of previous time range of the version */
    public var previousCount: Int64?

    public init(version: String?, count: Int64?, previousCount: Int64?) {
        self.version = version
        self.count = count
        self.previousCount = previousCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case version
        case count
        case previousCount = "previous_count"
    }

}
