//
// WebSocketContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A websocket reference */
public struct WebSocketContainer: Codable {

    /** WebSocket URL */
    public var url: String

    public init(url: String) {
        self.url = url
    }

}
