//
// XamarinSolution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct XamarinSolution: Codable {

    /** Path to solution */
    public var path: String
    /** Solution configurations */
    public var configurations: [String]
    /** Solution default configuration */
    public var defaultConfiguration: String?

    public init(path: String, configurations: [String], defaultConfiguration: String?) {
        self.path = path
        self.configurations = configurations
        self.defaultConfiguration = defaultConfiguration
    }

}
