//
// XcodeScheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct XcodeScheme: Codable {

    /** Scheme name */
    public var name: String
    /** Does scheme have a test action? */
    public var hasTestAction: Bool
    /** Build configuration set in Archive action */
    public var archiveConfiguration: String?
    public var archiveProject: XcodeSchemeArchiveProject?

    public init(name: String, hasTestAction: Bool, archiveConfiguration: String?, archiveProject: XcodeSchemeArchiveProject?) {
        self.name = name
        self.hasTestAction = hasTestAction
        self.archiveConfiguration = archiveConfiguration
        self.archiveProject = archiveProject
    }

}
