//
// XcodeVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Xcode version */
public struct XcodeVersion: Codable {

    /** The version name */
    public var name: String?
    /** If the Xcode is latest stable */
    public var current: Bool?

    public init(name: String?, current: Bool?) {
        self.name = name
        self.current = current
    }

}
